In [1]:
import pandas as pd

In [2]:
rental_data_sf = pd.read_csv("../data/curated/rental_data_sf.csv")

In [3]:
rental_data_sf.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,SA2_CODE21,SA2_NAME21
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,$120.00,"[-37.8353315, 145.1114189]",House,1,2,6,Single room in rooming house - CURRENTLY NO RO...,"['** BOOK INSPECTION ONLINE **', '*Currently n...","['Furnished*', 'Broadband internet access*', '...",No NBN,120,3127,POINT (145.1114189 -37.8353315),207031167.0,Surrey Hills (East) - Mont Albert
1,30 Daly Boulevard Highton VIC 3216,$130,"[-38.1962932, 144.3060777]",House,9,2,2,Student Accommodation - 1 Room Available!,['We have 1 Rooms Available to Rent.Room 2 - $...,"['Gas*', 'Internal Laundry*', 'Secure Parking*...",nbn® Fibre to the Node (FTTN) is available in ...,130,3216,POINT (144.3060777 -38.1962932),203021042.0,Highton
2,Berth 5274 Martha Cove Waterway Safety Beach V...,$140 per week,"[-38.3138012, 145.0045603]",House,1,1,0,Boat Berth B5274,['BOAT BERTH AVAILABLE-B5274-Located in Martha...,[],No NBN,140,3936,POINT (145.0045603 -38.3138012),214021377.0,Dromana
3,18 Cedarville Close Highton VIC 3216,$140,"[-38.19508, 144.3154857]",House,1,2,6,Room 4 rent!,['Rooms for rent in this student share house. ...,"['Built in wardrobes', 'Internal Laundry', 'Ga...",nbn® Fibre to the Premises (FTTP) is available...,140,3216,POINT (144.3154857 -38.19508),203021042.0,Highton
4,123 Thornhill Road Highton VIC 3216,$150,"[-38.1845196, 144.3107906]",House,1,4,3,Room for rent near Uni,['Rooms within walking distance to Waurn Ponds...,"['Ensuite', 'Furnished', 'Built in wardrobes*'...",nbn® Fibre to the Node (FTTN) is available in ...,150,3216,POINT (144.3107906 -38.1845196),203021042.0,Highton

In [4]:
crime_data =  pd.read_csv("../data/raw/crime_data.csv")

In [25]:
crime_data_23 = crime_data[crime_data['Year'] == 2023]
crime_data_23_agg = crime_data_23.groupby(['Postcode']).agg({'Offence Count': 'sum'})
crime_data_23_agg.reset_index()

crime_data_22 = crime_data[crime_data['Year'] == 2022]
crime_data_22_agg = crime_data_22.groupby(['Postcode']).agg({'Offence Count': 'sum'})
crime_data_22_agg.reset_index()

crime_data_21 = crime_data[crime_data['Year'] == 2022]
crime_data_21_agg = crime_data_21.groupby(['Postcode']).agg({'Offence Count': 'sum'})
crime_data_21_agg.reset_index()

     Postcode  Offence Count
0        3000            122
1        3002             18
2        3003             52
3        3004             24
4        3006             76
..        ...            ...
469      3984             19
470      3991              1
471      3992              2
472      3995             24
473      3996              3

[474 rows x 2 columns]

In [29]:
rental_data_crime_join = pd.merge(rental_data_sf, crime_data_23_agg, on='Postcode', how='left')
rental_data_crime_join = rental_data_crime_join.rename(columns={'Offence Count': 'Offence Count 2023'})

rental_data_crime_join = pd.merge(rental_data_crime_join, crime_data_22_agg, on='Postcode', how='left')
rental_data_crime_join = rental_data_crime_join.rename(columns={'Offence Count': 'Offence Count 2022'})

rental_data_crime_join = pd.merge(rental_data_crime_join, crime_data_21_agg, on='Postcode', how='left')
rental_data_crime_join = rental_data_crime_join.rename(columns={'Offence Count': 'Offence Count 2021'})

rental_data_crime_join.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,SA2_CODE21,SA2_NAME21,Offence Count 2023,Offence Count 2022,Offence Count 2021
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,$120.00,"[-37.8353315, 145.1114189]",House,1,2,6,Single room in rooming house - CURRENTLY NO RO...,"['** BOOK INSPECTION ONLINE **', '*Currently n...","['Furnished*', 'Broadband internet access*', '...",No NBN,120,3127,POINT (145.1114189 -37.8353315),207031167.0,Surrey Hills (East) - Mont Albert,29.0,21.0,21.0
1,30 Daly Boulevard Highton VIC 3216,$130,"[-38.1962932, 144.3060777]",House,9,2,2,Student Accommodation - 1 Room Available!,['We have 1 Rooms Available to Rent.Room 2 - $...,"['Gas*', 'Internal Laundry*', 'Secure Parking*...",nbn® Fibre to the Node (FTTN) is available in ...,130,3216,POINT (144.3060777 -38.1962932),203021042.0,Highton,121.0,83.0,83.0
2,Berth 5274 Martha Cove Waterway Safety Beach V...,$140 per week,"[-38.3138012, 145.0045603]",House,1,1,0,Boat Berth B5274,['BOAT BERTH AVAILABLE-B5274-Located in Martha...,[],No NBN,140,3936,POINT (145.0045603 -38.3138012),214021377.0,Dromana,17.0,12.0,12.0
3,18 Cedarville Close Highton VIC 3216,$140,"[-38.19508, 144.3154857]",House,1,2,6,Room 4 rent!,['Rooms for rent in this student share house. ...,"['Built in wardrobes', 'Internal Laundry', 'Ga...",nbn® Fibre to the Premises (FTTP) is available...,140,3216,POINT (144.3154857 -38.19508),203021042.0,Highton,121.0,83.0,83.0
4,123 Thornhill Road Highton VIC 3216,$150,"[-38.1845196, 144.3107906]",House,1,4,3,Room for rent near Uni,['Rooms within walking distance to Waurn Ponds...,"['Ensuite', 'Furnished', 'Built in wardrobes*'...",nbn® Fibre to the Node (FTTN) is available in ...,150,3216,POINT (144.3107906 -38.1845196),203021042.0,Highton,121.0,83.0,83.0

In [30]:
folder_path = '../data/curated/'
file_name = 'rental_data_crime_join.csv'

rental_data_crime_join.to_csv(folder_path + file_name, index=False)