In [29]:
import pandas as pd

In [30]:
rental_school_hospital = pd.read_csv("../data/curated/rental_data_distance_sf.csv")
rental_crime = pd.read_csv("../data/curated/rental_data_crime_join.csv")
postcode_2011 = pd.read_csv("../data/curated/postcode_info_2011.csv")
postcode_2016 = pd.read_csv("../data/curated/postcode_info_2011.csv")
postcode_2021 = pd.read_csv("../data/curated/postcode_info_2011.csv")

In [31]:
# lowercase column names
postcode_2011.columns = postcode_2011.columns.str.lower()
postcode_2016.columns = postcode_2016.columns.str.lower()
postcode_2021.columns = postcode_2021.columns.str.lower()
rental_crime.columns = rental_crime.columns.str.lower()
rental_school_hospital.columns = rental_school_hospital.columns.str.lower()

In [32]:
# drop duplicate properties
rental_school_hospital = rental_school_hospital.drop_duplicates(
    subset=["name", "cost_text", "coordinates", "property type", "beds", "baths", "parking"])

rental_crime = rental_crime.drop_duplicates(
    subset=["name", "cost_text", "coordinates", "property type", "beds", "baths", "parking"])

In [33]:
# lowercase column names
postcode_2011.columns = postcode_2011.columns.str.lower()
postcode_2016.columns = postcode_2016.columns.str.lower()
postcode_2021.columns = postcode_2021.columns.str.lower()


# add year in column name for postcode info dataframes
postcode_2011.columns = [col + " 2011" for col in postcode_2011.columns]
postcode_2016.columns = [col + " 2016" for col in postcode_2016.columns]
postcode_2021.columns = [col + " 2021" for col in postcode_2021.columns]

In [34]:
postcode_2021

,postcode 2021,estimated resident population (no.) 2021,employed (no.) 2021,unemployed (no.) 2021,in the labour force (no.) 2021,total persons aged 15 years and over (no.) 2021,land area (ha) 2021,total families (no.) 2021,total dwellings (no.) 2021,median equivalised total household income (weekly) ($) 2021,median weekly household rental payment ($) 2021,average family size (no. of persons) 2021
0,3000,0.0,55833.0,4270.0,60108.0,97390.0,0.0,23110.0,0.0,1017.090909,402.090909,2.481818
1,3002,0.0,3122.0,109.0,3234.0,4630.0,0.0,1087.0,0.0,1504.000000,420.000000,2.300000
2,3003,0.0,7840.0,706.0,8558.0,13921.0,0.0,3015.0,0.0,1014.000000,395.000000,2.500000
3,3004,0.0,38469.0,2536.0,41011.0,63808.0,0.0,15049.0,0.0,1120.000000,417.625000,2.387500
4,3006,0.0,12197.0,696.0,12899.0,19496.0,0.0,4936.0,0.0,1257.000000,483.500000,2.350000
...,...,...,...,...,...,...,...,...,...,...,...,...
422,3988,0.0,4020.0,172.0,4192.0,6995.0,0.0,2434.0,0.0,630.000000,195.000000,3.000000
423,3991,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
424,3992,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
425,3995,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
426,3996,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000

In [35]:
rental_crime

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,nbn,weekly rent amount,postcode,geometry,sa2_code21,sa2_name21,offence count 2023,offence count 2022,offence count 2021
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,$120.00,"[-37.8353315, 145.1114189]",House,1,2,6,Single room in rooming house - CURRENTLY NO RO...,"['** BOOK INSPECTION ONLINE **', '*Currently n...","['Furnished*', 'Broadband internet access*', '...",No NBN,120,3127,POINT (145.1114189 -37.8353315),207031167.0,Surrey Hills (East) - Mont Albert,29.0,21.0,21.0
1,30 Daly Boulevard Highton VIC 3216,$130,"[-38.1962932, 144.3060777]",House,9,2,2,Student Accommodation - 1 Room Available!,['We have 1 Rooms Available to Rent.Room 2 - $...,"['Gas*', 'Internal Laundry*', 'Secure Parking*...",nbn® Fibre to the Node (FTTN) is available in ...,130,3216,POINT (144.3060777 -38.1962932),203021042.0,Highton,121.0,83.0,83.0
2,Berth 5274 Martha Cove Waterway Safety Beach V...,$140 per week,"[-38.3138012, 145.0045603]",House,1,1,0,Boat Berth B5274,['BOAT BERTH AVAILABLE-B5274-Located in Martha...,[],No NBN,140,3936,POINT (145.0045603 -38.3138012),214021377.0,Dromana,17.0,12.0,12.0
3,18 Cedarville Close Highton VIC 3216,$140,"[-38.19508, 144.3154857]",House,1,2,6,Room 4 rent!,['Rooms for rent in this student share house. ...,"['Built in wardrobes', 'Internal Laundry', 'Ga...",nbn® Fibre to the Premises (FTTP) is available...,140,3216,POINT (144.3154857 -38.19508),203021042.0,Highton,121.0,83.0,83.0
4,123 Thornhill Road Highton VIC 3216,$150,"[-38.1845196, 144.3107906]",House,1,4,3,Room for rent near Uni,['Rooms within walking distance to Waurn Ponds...,"['Ensuite', 'Furnished', 'Built in wardrobes*'...",nbn® Fibre to the Node (FTTN) is available in ...,150,3216,POINT (144.3107906 -38.1845196),203021042.0,Highton,121.0,83.0,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11404,Enquire For Address Brighton VIC 3186,"$4,400.00","[-37.9044002, 144.9997396]",House,4,4,2,Golden Mile Luxury,"['Inspect by Appointment Only ', 'This family ...","['Study', 'Swimming Pool', 'Ducted Cooling', '...",No NBN,4400,3186,POINT (144.9997396 -37.9044002),208011169.0,Brighton (Vic.),37.0,29.0,29.0
11405,335 The Esplanade Indented Head VIC 3223,"$4,700 pw /$700 pn High, $3,775 pw/$545 pn Low","[-38.1439923, 144.7147899]",House,4,3,0,"335 The Esplanade, Indented Head",['This stylish 4 bedroom home will surely make...,"['Ensuite', 'Deck', 'Dishwasher', 'Ducted Heat...",No NBN,4700,3223,POINT (144.7147899 -38.1439923),203031051.0,Portarlington,13.0,6.0,6.0
11406,8701/7 Riverside Quay Southbank VIC 3006,"$5,000.00","[-37.8213342, 144.9646982]",Apartment / Unit / Flat,3,3,4,On Top of the World,"[""A brilliant opportunity to lease the exclusi...",[],nbn® Fibre to the Building (FTTB) is available...,5000,3006,POINT (144.9646982 -37.8213342),206041508.0,Southbank (West) - South Wharf,67.0,76.0,76.0
11407,1 Weston Street Balwyn VIC 3103,"$9,950 weekly","[-37.8117577, 145.0775507]",House,6,7,8,"Lifestyle, Modern & Luxury Living Awaits",['**Scheduling your property inspection is now...,"['Air conditioning*', 'Built in wardrobes*', '...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,POINT (145.0775507 -37.8117577),207011147.0,Balwyn,14.0,11.0,11.0
11408,1 Weston Street Balwyn VIC 3103,"$9,950","[-37.8117577, 145.0775507]",House,6,7,8,The Ultimate Luxury Living,['Introducing an extraordinary property that e...,"['Furnished', 'Air conditioning*', 'Built in w...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,POINT (145.0775507 -37.8117577),207011147.0,Balwyn,14.0,11.0,11.0

In [36]:
rental_crime = rental_crime[["name", "offence count 2023", "offence count 2022", "offence count 2021"]]
rental_crime

,name,offence count 2023,offence count 2022,offence count 2021
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,29.0,21.0,21.0
1,30 Daly Boulevard Highton VIC 3216,121.0,83.0,83.0
2,Berth 5274 Martha Cove Waterway Safety Beach V...,17.0,12.0,12.0
3,18 Cedarville Close Highton VIC 3216,121.0,83.0,83.0
4,123 Thornhill Road Highton VIC 3216,121.0,83.0,83.0
...,...,...,...,...
11404,Enquire For Address Brighton VIC 3186,37.0,29.0,29.0
11405,335 The Esplanade Indented Head VIC 3223,13.0,6.0,6.0
11406,8701/7 Riverside Quay Southbank VIC 3006,67.0,76.0,76.0
11407,1 Weston Street Balwyn VIC 3103,14.0,11.0,11.0
11408,1 Weston Street Balwyn VIC 3103,14.0,11.0,11.0

In [37]:
# impute missing values as 0
rental_crime["offence count 2023"] = rental_crime["offence count 2023"].fillna(0)
rental_crime["offence count 2022"] = rental_crime["offence count 2022"].fillna(0)
rental_crime["offence count 2021"] = rental_crime["offence count 2021"].fillna(0)

/var/folders/wb/9whmmh7s5bvf174ppr2jwprr0000gn/T/ipykernel_61562/1712784008.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_crime["offence count 2023"] = rental_crime["offence count 2023"].fillna(0)
/var/folders/wb/9whmmh7s5bvf174ppr2jwprr0000gn/T/ipykernel_61562/1712784008.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_crime["offence count 2022"] = rental_crime["offence count 2022"].fillna(0)
/var/folders/wb/9whmmh7s5bvf174ppr2jwprr0000gn/T/ipykernel_61562/1712784008.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_crime["offence count 2021"] = rental_crime["offence count 2021"].fillna(0)

In [38]:
rental_school_hospital

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,...,postcode,geometry,sa2_code21,sa2_name21,closest primary school,distance primary school,closest secondary school,distance secondary school,closest university campus,distance university campus
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,$120.00,"[-37.8353315, 145.1114189]",House,1,2,6,Single room in rooming house - CURRENTLY NO RO...,"['** BOOK INSPECTION ONLINE **', '*Currently n...","['Furnished*', 'Broadband internet access*', '...",...,3127,POINT (145.1114189 -37.8353315),207031167.0,Surrey Hills (East) - Mont Albert,our lady of perpetual succour,0.586504,our lady of sion college,2.491226,monash university-notting hill,7.430317
1,30 Daly Boulevard Highton VIC 3216,$130,"[-38.1962932, 144.3060777]",House,9,2,2,Student Accommodation - 1 Room Available!,['We have 1 Rooms Available to Rent.Room 2 - $...,"['Gas*', 'Internal Laundry*', 'Secure Parking*...",...,3216,POINT (144.3060777 -38.1962932),203021042.0,Highton,christian college geelong,1.372612,grovedale college,2.438191,deakin university-waurn ponds,0.675843
2,Berth 5274 Martha Cove Waterway Safety Beach V...,$140 per week,"[-38.3138012, 145.0045603]",House,1,1,0,Boat Berth B5274,['BOAT BERTH AVAILABLE-B5274-Located in Martha...,[],...,3936,POINT (145.0045603 -38.3138012),214021377.0,Dromana,dromana primary,4.858273,dromana secondary college,3.301447,monash university-notting hill,47.278807
3,18 Cedarville Close Highton VIC 3216,$140,"[-38.19508, 144.3154857]",House,1,2,6,Room 4 rent!,['Rooms for rent in this student share house. ...,"['Built in wardrobes', 'Internal Laundry', 'Ga...",...,3216,POINT (144.3154857 -38.19508),203021042.0,Highton,christian college geelong,1.114181,grovedale college,1.998214,deakin university-waurn ponds,1.502495
4,123 Thornhill Road Highton VIC 3216,$150,"[-38.1845196, 144.3107906]",House,1,4,3,Room for rent near Uni,['Rooms within walking distance to Waurn Ponds...,"['Ensuite', 'Furnished', 'Built in wardrobes*'...",...,3216,POINT (144.3107906 -38.1845196),203021042.0,Highton,christian college geelong,0.215009,belmont high,1.989564,deakin university-waurn ponds,1.862509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11404,Enquire For Address Brighton VIC 3186,"$4,400.00","[-37.9044002, 144.9997396]",House,4,4,2,Golden Mile Luxury,"['Inspect by Appointment Only ', 'This family ...","['Study', 'Swimming Pool', 'Ducted Cooling', '...",...,3186,POINT (144.9997396 -37.9044002),208011169.0,Brighton (Vic.),firbank grammar,0.311431,star of the sea college,0.891118,monash university-notting hill,11.507926
11405,335 The Esplanade Indented Head VIC 3223,"$4,700 pw /$700 pn High, $3,775 pw/$545 pn Low","[-38.1439923, 144.7147899]",House,4,3,0,"335 The Esplanade, Indented Head",['This stylish 4 bedroom home will surely make...,"['Ensuite', 'Deck', 'Dishwasher', 'Ducted Heat...",...,3223,POINT (144.7147899 -38.1439923),203031051.0,Portarlington,st leonards primary,3.095969,bellarine secondary college,14.695112,the university of melbourne-parkville,44.215772
11406,8701/7 Riverside Quay Southbank VIC 3006,"$5,000.00","[-37.8213342, 144.9646982]",Apartment / Unit / Flat,3,3,4,On Top of the World,"[""A brilliant opportunity to lease the exclusi...",[],...,3006,POINT (144.9646982 -37.8213342),206041508.0,Southbank (West) - South Wharf,south melbourne primary,1.327110,victorian college of the arts secondary,0.766691,the university of melbourne-southbank,0.615756
11407,1 Weston Street Balwyn VIC 3103,"$9,950 weekly","[-37.8117577, 145.0775507]",House,6,7,8,"Lifestyle, Modern & Luxury Living Awaits",['**Scheduling your property inspection is now...,"['Air conditioning*', 'Built in wardrobes*', '...",...,3103,POINT (145.0775507 -37.8117577),207011147.0,Balwyn,balwyn primary,0.414506,canterbury girls secondary college,1.204451,the university of melbourne-parkville,10.386190
11408,1 Weston Street Balwyn VIC 3103,"$9,950","[-37.8117577, 145.0775507]",House,6,7,8,The Ultimate Luxury Living,['Introducing an extraordinary property that e...,"['Furnished', 'Air conditioning*', 'Built in w...",...,3103,POINT (145.0775507 -37.8117577),207011147.0,Balwyn,balwyn primary,0.414506,canterbury girls secondary college,1.204451,the university of melbourne-parkville,10.386190

# Merge rental_data_school_hopsital with rental_crime

In [39]:
rental_merged = pd.merge(rental_school_hospital, rental_crime, on="name", how="inner")
rental_merged

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,...,sa2_name21,closest primary school,distance primary school,closest secondary school,distance secondary school,closest university campus,distance university campus,offence count 2023,offence count 2022,offence count 2021
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,$120.00,"[-37.8353315, 145.1114189]",House,1,2,6,Single room in rooming house - CURRENTLY NO RO...,"['** BOOK INSPECTION ONLINE **', '*Currently n...","['Furnished*', 'Broadband internet access*', '...",...,Surrey Hills (East) - Mont Albert,our lady of perpetual succour,0.586504,our lady of sion college,2.491226,monash university-notting hill,7.430317,29.0,21.0,21.0
1,30 Daly Boulevard Highton VIC 3216,$130,"[-38.1962932, 144.3060777]",House,9,2,2,Student Accommodation - 1 Room Available!,['We have 1 Rooms Available to Rent.Room 2 - $...,"['Gas*', 'Internal Laundry*', 'Secure Parking*...",...,Highton,christian college geelong,1.372612,grovedale college,2.438191,deakin university-waurn ponds,0.675843,121.0,83.0,83.0
2,Berth 5274 Martha Cove Waterway Safety Beach V...,$140 per week,"[-38.3138012, 145.0045603]",House,1,1,0,Boat Berth B5274,['BOAT BERTH AVAILABLE-B5274-Located in Martha...,[],...,Dromana,dromana primary,4.858273,dromana secondary college,3.301447,monash university-notting hill,47.278807,17.0,12.0,12.0
3,18 Cedarville Close Highton VIC 3216,$140,"[-38.19508, 144.3154857]",House,1,2,6,Room 4 rent!,['Rooms for rent in this student share house. ...,"['Built in wardrobes', 'Internal Laundry', 'Ga...",...,Highton,christian college geelong,1.114181,grovedale college,1.998214,deakin university-waurn ponds,1.502495,121.0,83.0,83.0
4,123 Thornhill Road Highton VIC 3216,$150,"[-38.1845196, 144.3107906]",House,1,4,3,Room for rent near Uni,['Rooms within walking distance to Waurn Ponds...,"['Ensuite', 'Furnished', 'Built in wardrobes*'...",...,Highton,christian college geelong,0.215009,belmont high,1.989564,deakin university-waurn ponds,1.862509,121.0,83.0,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11412,8701/7 Riverside Quay Southbank VIC 3006,"$5,000.00","[-37.8213342, 144.9646982]",Apartment / Unit / Flat,3,3,4,On Top of the World,"[""A brilliant opportunity to lease the exclusi...",[],...,Southbank (West) - South Wharf,south melbourne primary,1.327110,victorian college of the arts secondary,0.766691,the university of melbourne-southbank,0.615756,67.0,76.0,76.0
11413,1 Weston Street Balwyn VIC 3103,"$9,950 weekly","[-37.8117577, 145.0775507]",House,6,7,8,"Lifestyle, Modern & Luxury Living Awaits",['**Scheduling your property inspection is now...,"['Air conditioning*', 'Built in wardrobes*', '...",...,Balwyn,balwyn primary,0.414506,canterbury girls secondary college,1.204451,the university of melbourne-parkville,10.386190,14.0,11.0,11.0
11414,1 Weston Street Balwyn VIC 3103,"$9,950 weekly","[-37.8117577, 145.0775507]",House,6,7,8,"Lifestyle, Modern & Luxury Living Awaits",['**Scheduling your property inspection is now...,"['Air conditioning*', 'Built in wardrobes*', '...",...,Balwyn,balwyn primary,0.414506,canterbury girls secondary college,1.204451,the university of melbourne-parkville,10.386190,14.0,11.0,11.0
11415,1 Weston Street Balwyn VIC 3103,"$9,950","[-37.8117577, 145.0775507]",House,6,7,8,The Ultimate Luxury Living,['Introducing an extraordinary property that e...,"['Furnished', 'Air conditioning*', 'Built in w...",...,Balwyn,balwyn primary,0.414506,canterbury girls secondary college,1.204451,the university of melbourne-parkville,10.386190,14.0,11.0,11.0
11416,1 Weston Street Balwyn VIC 3103,"$9,950","[-37.8117577, 145.0775507]",House,6,7,8,The Ultimate Luxury Living,['Introducing an extraordinary property that e...,"['Furnished', 'Air conditioning*', 'Built in w...",...,Balwyn,balwyn primary,0.414506,canterbury girls secondary college,1.204451,the university of melbourne-parkville,10.386190,14.0,11.0,11.0

# Merge different years' postcode data together

In [40]:
# merge 2011 and 2016
postcode_merged = pd.merge(postcode_2011, postcode_2016, left_on = "postcode 2011", right_on = "postcode 2016",
                           how="inner")
postcode_merged = postcode_merged.drop("postcode 2011", axis=1)

postcode_merged

,estimated resident population (no.) 2011,employed (no.) 2011,unemployed (no.) 2011,in the labour force (no.) 2011,total persons aged 15 years and over (no.) 2011,land area (ha) 2011,total families (no.) 2011,total dwellings (no.) 2011,median equivalised total household income (weekly) ($) 2011,median weekly household rental payment ($) 2011,...,employed (no.) 2016,unemployed (no.) 2016,in the labour force (no.) 2016,total persons aged 15 years and over (no.) 2016,land area (ha) 2016,total families (no.) 2016,total dwellings (no.) 2016,median equivalised total household income (weekly) ($) 2016,median weekly household rental payment ($) 2016,average family size (no. of persons) 2016
0,0.0,55833.0,4270.0,60108.0,97390.0,0.0,23110.0,0.0,1017.090909,402.090909,...,55833.0,4270.0,60108.0,97390.0,0.0,23110.0,0.0,1017.090909,402.090909,2.481818
1,0.0,3122.0,109.0,3234.0,4630.0,0.0,1087.0,0.0,1504.000000,420.000000,...,3122.0,109.0,3234.0,4630.0,0.0,1087.0,0.0,1504.000000,420.000000,2.300000
2,0.0,7840.0,706.0,8558.0,13921.0,0.0,3015.0,0.0,1014.000000,395.000000,...,7840.0,706.0,8558.0,13921.0,0.0,3015.0,0.0,1014.000000,395.000000,2.500000
3,0.0,38469.0,2536.0,41011.0,63808.0,0.0,15049.0,0.0,1120.000000,417.625000,...,38469.0,2536.0,41011.0,63808.0,0.0,15049.0,0.0,1120.000000,417.625000,2.387500
4,0.0,12197.0,696.0,12899.0,19496.0,0.0,4936.0,0.0,1257.000000,483.500000,...,12197.0,696.0,12899.0,19496.0,0.0,4936.0,0.0,1257.000000,483.500000,2.350000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,0.0,4020.0,172.0,4192.0,6995.0,0.0,2434.0,0.0,630.000000,195.000000,...,4020.0,172.0,4192.0,6995.0,0.0,2434.0,0.0,630.000000,195.000000,3.000000
423,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,...,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
424,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,...,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
425,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,...,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
426,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,...,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000

In [41]:
# merge 2021 data with rest of postcode data
postcode_merged = pd.merge(postcode_merged, postcode_2021, left_on = "postcode 2016", right_on = "postcode 2021",
                           how="inner")
postcode_merged = postcode_merged.drop("postcode 2016", axis=1)
postcode_merged

,estimated resident population (no.) 2011,employed (no.) 2011,unemployed (no.) 2011,in the labour force (no.) 2011,total persons aged 15 years and over (no.) 2011,land area (ha) 2011,total families (no.) 2011,total dwellings (no.) 2011,median equivalised total household income (weekly) ($) 2011,median weekly household rental payment ($) 2011,...,employed (no.) 2021,unemployed (no.) 2021,in the labour force (no.) 2021,total persons aged 15 years and over (no.) 2021,land area (ha) 2021,total families (no.) 2021,total dwellings (no.) 2021,median equivalised total household income (weekly) ($) 2021,median weekly household rental payment ($) 2021,average family size (no. of persons) 2021
0,0.0,55833.0,4270.0,60108.0,97390.0,0.0,23110.0,0.0,1017.090909,402.090909,...,55833.0,4270.0,60108.0,97390.0,0.0,23110.0,0.0,1017.090909,402.090909,2.481818
1,0.0,3122.0,109.0,3234.0,4630.0,0.0,1087.0,0.0,1504.000000,420.000000,...,3122.0,109.0,3234.0,4630.0,0.0,1087.0,0.0,1504.000000,420.000000,2.300000
2,0.0,7840.0,706.0,8558.0,13921.0,0.0,3015.0,0.0,1014.000000,395.000000,...,7840.0,706.0,8558.0,13921.0,0.0,3015.0,0.0,1014.000000,395.000000,2.500000
3,0.0,38469.0,2536.0,41011.0,63808.0,0.0,15049.0,0.0,1120.000000,417.625000,...,38469.0,2536.0,41011.0,63808.0,0.0,15049.0,0.0,1120.000000,417.625000,2.387500
4,0.0,12197.0,696.0,12899.0,19496.0,0.0,4936.0,0.0,1257.000000,483.500000,...,12197.0,696.0,12899.0,19496.0,0.0,4936.0,0.0,1257.000000,483.500000,2.350000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,0.0,4020.0,172.0,4192.0,6995.0,0.0,2434.0,0.0,630.000000,195.000000,...,4020.0,172.0,4192.0,6995.0,0.0,2434.0,0.0,630.000000,195.000000,3.000000
423,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,...,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
424,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,...,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
425,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,...,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000
426,0.0,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,...,8111.0,391.0,8503.0,16628.0,0.0,5314.0,0.0,582.000000,230.000000,2.800000

# Merge postcode data with rental data

In [42]:
rental_merged = pd.merge(rental_merged, postcode_merged, left_on = "postcode", right_on = "postcode 2021", 
                              how="left")
rental_merged = rental_merged.drop("postcode 2021", axis=1)
rental_merged

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,...,employed (no.) 2021,unemployed (no.) 2021,in the labour force (no.) 2021,total persons aged 15 years and over (no.) 2021,land area (ha) 2021,total families (no.) 2021,total dwellings (no.) 2021,median equivalised total household income (weekly) ($) 2021,median weekly household rental payment ($) 2021,average family size (no. of persons) 2021
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,$120.00,"[-37.8353315, 145.1114189]",House,1,2,6,Single room in rooming house - CURRENTLY NO RO...,"['** BOOK INSPECTION ONLINE **', '*Currently n...","['Furnished*', 'Broadband internet access*', '...",...,20267.0,934.0,21200.0,33991.0,0.0,10901.0,0.0,1089.0,367.00,3.133333
1,30 Daly Boulevard Highton VIC 3216,$130,"[-38.1962932, 144.3060777]",House,9,2,2,Student Accommodation - 1 Room Available!,['We have 1 Rooms Available to Rent.Room 2 - $...,"['Gas*', 'Internal Laundry*', 'Secure Parking*...",...,25316.0,1259.0,26567.0,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000
2,Berth 5274 Martha Cove Waterway Safety Beach V...,$140 per week,"[-38.3138012, 145.0045603]",House,1,1,0,Boat Berth B5274,['BOAT BERTH AVAILABLE-B5274-Located in Martha...,[],...,3626.0,200.0,3823.0,7615.0,0.0,2547.0,0.0,628.0,271.00,2.700000
3,18 Cedarville Close Highton VIC 3216,$140,"[-38.19508, 144.3154857]",House,1,2,6,Room 4 rent!,['Rooms for rent in this student share house. ...,"['Built in wardrobes', 'Internal Laundry', 'Ga...",...,25316.0,1259.0,26567.0,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000
4,123 Thornhill Road Highton VIC 3216,$150,"[-38.1845196, 144.3107906]",House,1,4,3,Room for rent near Uni,['Rooms within walking distance to Waurn Ponds...,"['Ensuite', 'Furnished', 'Built in wardrobes*'...",...,25316.0,1259.0,26567.0,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11412,8701/7 Riverside Quay Southbank VIC 3006,"$5,000.00","[-37.8213342, 144.9646982]",Apartment / Unit / Flat,3,3,4,On Top of the World,"[""A brilliant opportunity to lease the exclusi...",[],...,12197.0,696.0,12899.0,19496.0,0.0,4936.0,0.0,1257.0,483.50,2.350000
11413,1 Weston Street Balwyn VIC 3103,"$9,950 weekly","[-37.8117577, 145.0775507]",House,6,7,8,"Lifestyle, Modern & Luxury Living Awaits",['**Scheduling your property inspection is now...,"['Air conditioning*', 'Built in wardrobes*', '...",...,16540.0,845.0,17386.0,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000
11414,1 Weston Street Balwyn VIC 3103,"$9,950 weekly","[-37.8117577, 145.0775507]",House,6,7,8,"Lifestyle, Modern & Luxury Living Awaits",['**Scheduling your property inspection is now...,"['Air conditioning*', 'Built in wardrobes*', '...",...,16540.0,845.0,17386.0,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000
11415,1 Weston Street Balwyn VIC 3103,"$9,950","[-37.8117577, 145.0775507]",House,6,7,8,The Ultimate Luxury Living,['Introducing an extraordinary property that e...,"['Furnished', 'Air conditioning*', 'Built in w...",...,16540.0,845.0,17386.0,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000
11416,1 Weston Street Balwyn VIC 3103,"$9,950","[-37.8117577, 145.0775507]",House,6,7,8,The Ultimate Luxury Living,['Introducing an extraordinary property that e...,"['Furnished', 'Air conditioning*', 'Built in w...",...,16540.0,845.0,17386.0,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000

In [43]:
# drop irrelevant columns
rental_merged = rental_merged.drop(["title", "description", "cost_text"], axis=1)
rental_merged

,name,coordinates,property type,beds,baths,parking,property features,nbn,weekly rent amount,postcode,...,employed (no.) 2021,unemployed (no.) 2021,in the labour force (no.) 2021,total persons aged 15 years and over (no.) 2021,land area (ha) 2021,total families (no.) 2021,total dwellings (no.) 2021,median equivalised total household income (weekly) ($) 2021,median weekly household rental payment ($) 2021,average family size (no. of persons) 2021
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,"[-37.8353315, 145.1114189]",House,1,2,6,"['Furnished*', 'Broadband internet access*', '...",No NBN,120,3127,...,20267.0,934.0,21200.0,33991.0,0.0,10901.0,0.0,1089.0,367.00,3.133333
1,30 Daly Boulevard Highton VIC 3216,"[-38.1962932, 144.3060777]",House,9,2,2,"['Gas*', 'Internal Laundry*', 'Secure Parking*...",nbn® Fibre to the Node (FTTN) is available in ...,130,3216,...,25316.0,1259.0,26567.0,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000
2,Berth 5274 Martha Cove Waterway Safety Beach V...,"[-38.3138012, 145.0045603]",House,1,1,0,[],No NBN,140,3936,...,3626.0,200.0,3823.0,7615.0,0.0,2547.0,0.0,628.0,271.00,2.700000
3,18 Cedarville Close Highton VIC 3216,"[-38.19508, 144.3154857]",House,1,2,6,"['Built in wardrobes', 'Internal Laundry', 'Ga...",nbn® Fibre to the Premises (FTTP) is available...,140,3216,...,25316.0,1259.0,26567.0,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000
4,123 Thornhill Road Highton VIC 3216,"[-38.1845196, 144.3107906]",House,1,4,3,"['Ensuite', 'Furnished', 'Built in wardrobes*'...",nbn® Fibre to the Node (FTTN) is available in ...,150,3216,...,25316.0,1259.0,26567.0,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11412,8701/7 Riverside Quay Southbank VIC 3006,"[-37.8213342, 144.9646982]",Apartment / Unit / Flat,3,3,4,[],nbn® Fibre to the Building (FTTB) is available...,5000,3006,...,12197.0,696.0,12899.0,19496.0,0.0,4936.0,0.0,1257.0,483.50,2.350000
11413,1 Weston Street Balwyn VIC 3103,"[-37.8117577, 145.0775507]",House,6,7,8,"['Air conditioning*', 'Built in wardrobes*', '...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,...,16540.0,845.0,17386.0,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000
11414,1 Weston Street Balwyn VIC 3103,"[-37.8117577, 145.0775507]",House,6,7,8,"['Air conditioning*', 'Built in wardrobes*', '...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,...,16540.0,845.0,17386.0,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000
11415,1 Weston Street Balwyn VIC 3103,"[-37.8117577, 145.0775507]",House,6,7,8,"['Furnished', 'Air conditioning*', 'Built in w...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,...,16540.0,845.0,17386.0,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000
11416,1 Weston Street Balwyn VIC 3103,"[-37.8117577, 145.0775507]",House,6,7,8,"['Furnished', 'Air conditioning*', 'Built in w...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,...,16540.0,845.0,17386.0,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000

In [44]:
rental_merged.isna().any()

name                                                           False
coordinates                                                    False
property type                                                  False
beds                                                           False
baths                                                          False
parking                                                        False
property features                                              False
nbn                                                            False
weekly rent amount                                             False
postcode                                                       False
geometry                                                       False
sa2_code21                                                      True
sa2_name21                                                      True
closest primary school                                         False
distance primary school                                        False
closest secondary school                                       False
distance secondary school                                      False
closest university campus                                      False
distance university campus                                     False
offence count 2023                                             False
offence count 2022                                             False
offence count 2021                                             False
estimated resident population (no.) 2011                       False
employed (no.) 2011                                            False
unemployed (no.) 2011                                          False
in the labour force (no.) 2011                                 False
total persons aged 15 years and over (no.) 2011                False
land area (ha) 2011                                            False
total families (no.) 2011                                      False
total dwellings (no.) 2011                                     False
median equivalised total household income (weekly) ($) 2011    False
median weekly household rental payment ($) 2011                False
average family size (no. of persons) 2011                      False
estimated resident population (no.) 2016                       False
employed (no.) 2016                                            False
unemployed (no.) 2016                                          False
in the labour force (no.) 2016                                 False
total persons aged 15 years and over (no.) 2016                False
land area (ha) 2016                                            False
total families (no.) 2016                                      False
total dwellings (no.) 2016                                     False
median equivalised total household income (weekly) ($) 2016    False
median weekly household rental payment ($) 2016                False
average family size (no. of persons) 2016                      False
estimated resident population (no.) 2021                       False
employed (no.) 2021                                            False
unemployed (no.) 2021                                          False
in the labour force (no.) 2021                                 False
total persons aged 15 years and over (no.) 2021                False
land area (ha) 2021                                            False
total families (no.) 2021                                      False
total dwellings (no.) 2021                                     False
median equivalised total household income (weekly) ($) 2021    False
median weekly household rental payment ($) 2021                False
average family size (no. of persons) 2021                      False
dtype: bool

# Merge rental data with supermarket data

In [45]:
supermarket_data = pd.read_csv("../data/curated/supermarket_data.csv")
supermarket_data.columns = supermarket_data.columns.str.lower()
# convert postcode to float
supermarket_data["postcode"] = pd.to_numeric(supermarket_data["postcode"], errors="coerce")
print(len(supermarket_data))
# drop non-numeric postcodes
print(len(supermarket_data[supermarket_data["postcode"].isna()]))
supermarket_data = supermarket_data.dropna(subset = ["postcode"])
print(len(supermarket_data))

484
39
445

In [46]:
print(len(rental_merged))

11417

In [47]:
supermarket_data[supermarket_data["postcode"] == 3216]

               town  postcode  total  major
34          Belmont    3216.0      5      2
176       Grovedale    3216.0      5      5
177  Grovedale East    3216.0      1      1
195         Highton    3216.0      2      2
460     Waurn Ponds    3216.0      1      1

In [48]:
supermarket_data["postcode"].value_counts()

postcode
3216.0    5
3023.0    5
3030.0    4
3977.0    4
3350.0    4
         ..
3854.0    1
3146.0    1
3043.0    1
3437.0    1
3717.0    1
Name: count, Length: 344, dtype: int64

In [49]:
# merge rows with same postcode but different town names together
supermarket_data = supermarket_data.groupby("postcode").sum().reset_index()
supermarket_data.value_counts()

postcode  town                                   total  major
3000.0    Melbourne                              11     6        1
3523.0    Heathcote                              2      2        1
3556.0    Eaglehawk                              1      1        1
3555.0    Golden SquareKangaroo Flat             6      5        1
3551.0    Maiden Gully                           1      1        1
                                                                ..
3155.0    BoroniaBoronia HeightsBoronia Village  6      3        1
3153.0    BayswaterBayswater North               5      3        1
3152.0    Wantirna South                         4      3        1
3151.0    Burwood East                           3      2        1
3995.0    Wonthaggi                              3      3        1
Name: count, Length: 344, dtype: int64

In [50]:
supermarket_data[supermarket_data["postcode"] == 3216]

     postcode                                              town  total  major
159    3216.0  BelmontGrovedaleGrovedale EastHightonWaurn Ponds     14     11

In [51]:
# merge rental data and supermarket data
rental_merged = pd.merge(rental_merged, supermarket_data, how = "left", on="postcode")

In [52]:
rental_merged

,name,coordinates,property type,beds,baths,parking,property features,nbn,weekly rent amount,postcode,...,total persons aged 15 years and over (no.) 2021,land area (ha) 2021,total families (no.) 2021,total dwellings (no.) 2021,median equivalised total household income (weekly) ($) 2021,median weekly household rental payment ($) 2021,average family size (no. of persons) 2021,town,total,major
0,Rooms/227 Elgar Road Surrey Hills VIC 3127,"[-37.8353315, 145.1114189]",House,1,2,6,"['Furnished*', 'Broadband internet access*', '...",No NBN,120,3127,...,33991.0,0.0,10901.0,0.0,1089.0,367.00,3.133333,Mont AlbertSurrey Hills,2.0,2.0
1,30 Daly Boulevard Highton VIC 3216,"[-38.1962932, 144.3060777]",House,9,2,2,"['Gas*', 'Internal Laundry*', 'Secure Parking*...",nbn® Fibre to the Node (FTTN) is available in ...,130,3216,...,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000,BelmontGrovedaleGrovedale EastHightonWaurn Ponds,14.0,11.0
2,Berth 5274 Martha Cove Waterway Safety Beach V...,"[-38.3138012, 145.0045603]",House,1,1,0,[],No NBN,140,3936,...,7615.0,0.0,2547.0,0.0,628.0,271.00,2.700000,Dromana,1.0,1.0
3,18 Cedarville Close Highton VIC 3216,"[-38.19508, 144.3154857]",House,1,2,6,"['Built in wardrobes', 'Internal Laundry', 'Ga...",nbn® Fibre to the Premises (FTTP) is available...,140,3216,...,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000,BelmontGrovedaleGrovedale EastHightonWaurn Ponds,14.0,11.0
4,123 Thornhill Road Highton VIC 3216,"[-38.1845196, 144.3107906]",House,1,4,3,"['Ensuite', 'Furnished', 'Built in wardrobes*'...",nbn® Fibre to the Node (FTTN) is available in ...,150,3216,...,43134.0,0.0,14051.0,0.0,729.5,269.25,2.925000,BelmontGrovedaleGrovedale EastHightonWaurn Ponds,14.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11412,8701/7 Riverside Quay Southbank VIC 3006,"[-37.8213342, 144.9646982]",Apartment / Unit / Flat,3,3,4,[],nbn® Fibre to the Building (FTTB) is available...,5000,3006,...,19496.0,0.0,4936.0,0.0,1257.0,483.50,2.350000,Southbank,1.0,0.0
11413,1 Weston Street Balwyn VIC 3103,"[-37.8117577, 145.0775507]",House,6,7,8,"['Air conditioning*', 'Built in wardrobes*', '...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,...,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000,Balwyn,4.0,4.0
11414,1 Weston Street Balwyn VIC 3103,"[-37.8117577, 145.0775507]",House,6,7,8,"['Air conditioning*', 'Built in wardrobes*', '...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,...,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000,Balwyn,4.0,4.0
11415,1 Weston Street Balwyn VIC 3103,"[-37.8117577, 145.0775507]",House,6,7,8,"['Furnished', 'Air conditioning*', 'Built in w...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,...,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000,Balwyn,4.0,4.0
11416,1 Weston Street Balwyn VIC 3103,"[-37.8117577, 145.0775507]",House,6,7,8,"['Furnished', 'Air conditioning*', 'Built in w...",nbn® Hybrid Fibre Coaxial (HFC) is available i...,9950,3103,...,29273.0,0.0,9566.0,0.0,987.0,397.50,3.150000,Balwyn,4.0,4.0

In [53]:
rental_merged.isna().any()

name                                                           False
coordinates                                                    False
property type                                                  False
beds                                                           False
baths                                                          False
parking                                                        False
property features                                              False
nbn                                                            False
weekly rent amount                                             False
postcode                                                       False
geometry                                                       False
sa2_code21                                                      True
sa2_name21                                                      True
closest primary school                                         False
distance primary school                                        False
closest secondary school                                       False
distance secondary school                                      False
closest university campus                                      False
distance university campus                                     False
offence count 2023                                             False
offence count 2022                                             False
offence count 2021                                             False
estimated resident population (no.) 2011                       False
employed (no.) 2011                                            False
unemployed (no.) 2011                                          False
in the labour force (no.) 2011                                 False
total persons aged 15 years and over (no.) 2011                False
land area (ha) 2011                                            False
total families (no.) 2011                                      False
total dwellings (no.) 2011                                     False
median equivalised total household income (weekly) ($) 2011    False
median weekly household rental payment ($) 2011                False
average family size (no. of persons) 2011                      False
estimated resident population (no.) 2016                       False
employed (no.) 2016                                            False
unemployed (no.) 2016                                          False
in the labour force (no.) 2016                                 False
total persons aged 15 years and over (no.) 2016                False
land area (ha) 2016                                            False
total families (no.) 2016                                      False
total dwellings (no.) 2016                                     False
median equivalised total household income (weekly) ($) 2016    False
median weekly household rental payment ($) 2016                False
average family size (no. of persons) 2016                      False
estimated resident population (no.) 2021                       False
employed (no.) 2021                                            False
unemployed (no.) 2021                                          False
in the labour force (no.) 2021                                 False
total persons aged 15 years and over (no.) 2021                False
land area (ha) 2021                                            False
total families (no.) 2021                                      False
total dwellings (no.) 2021                                     False
median equivalised total household income (weekly) ($) 2021    False
median weekly household rental payment ($) 2021                False
average family size (no. of persons) 2021                      False
town                                                            True
total                                                           True
major                                                           True
dtype: bool

In [54]:
print(len(rental_merged))
# drop rows with null value for supermarkets after merge
rental_merged = rental_merged.dropna(subset=["total"])
print(len(rental_merged))

11417
10358

In [55]:
rental_merged.isna().any()

name                                                           False
coordinates                                                    False
property type                                                  False
beds                                                           False
baths                                                          False
parking                                                        False
property features                                              False
nbn                                                            False
weekly rent amount                                             False
postcode                                                       False
geometry                                                       False
sa2_code21                                                      True
sa2_name21                                                      True
closest primary school                                         False
distance primary school                                        False
closest secondary school                                       False
distance secondary school                                      False
closest university campus                                      False
distance university campus                                     False
offence count 2023                                             False
offence count 2022                                             False
offence count 2021                                             False
estimated resident population (no.) 2011                       False
employed (no.) 2011                                            False
unemployed (no.) 2011                                          False
in the labour force (no.) 2011                                 False
total persons aged 15 years and over (no.) 2011                False
land area (ha) 2011                                            False
total families (no.) 2011                                      False
total dwellings (no.) 2011                                     False
median equivalised total household income (weekly) ($) 2011    False
median weekly household rental payment ($) 2011                False
average family size (no. of persons) 2011                      False
estimated resident population (no.) 2016                       False
employed (no.) 2016                                            False
unemployed (no.) 2016                                          False
in the labour force (no.) 2016                                 False
total persons aged 15 years and over (no.) 2016                False
land area (ha) 2016                                            False
total families (no.) 2016                                      False
total dwellings (no.) 2016                                     False
median equivalised total household income (weekly) ($) 2016    False
median weekly household rental payment ($) 2016                False
average family size (no. of persons) 2016                      False
estimated resident population (no.) 2021                       False
employed (no.) 2021                                            False
unemployed (no.) 2021                                          False
in the labour force (no.) 2021                                 False
total persons aged 15 years and over (no.) 2021                False
land area (ha) 2021                                            False
total families (no.) 2021                                      False
total dwellings (no.) 2021                                     False
median equivalised total household income (weekly) ($) 2021    False
median weekly household rental payment ($) 2021                False
average family size (no. of persons) 2021                      False
town                                                           False
total                                                          False
major                                                          False
dtype: bool