In [ ]:
import geopandas as gpd
import pandas as pd

In [ ]:
open_spaces_sf = gpd.read_file("../data/raw/open_space/VPA_Draft_Open_Space_Data.shp")
sa2_districts_sf = gpd.read_file("../data/landing/sa2/SA2_2021_AUST_GDA2020.shp")

open_spaces_sf.head()

In [ ]:
sa2_districts_sf.columns

Add the SA2 district for each open space

In [3]:
joined = gpd.sjoin(open_spaces_sf, sa2_districts_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

joined.head()

/root/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):
/tmp/ipykernel_627/1156676244.py:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: EPSG:7844

  joined = gpd.sjoin(open_spaces_sf, sa2_districts_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

,FID,LGA,VM_PARCEL_,VM_PARCE_1,DATA_SOURC,OS_CATEGOR,OS_CATEG_2,OWNER_TYPE,PARK_NAME,OS_STATUS,...,MANAGER_NA,OWNER_NAME,Image_URL,VPA_ID,SHAPE_Leng,SHAPE_Area,geometry,index_right,SA2_CODE21,SA2_NAME21
0,1,BOROONDARA,3\LP28215,95086,VM Features of Interest,Tertiary institutions,Not applicable,State Government,Swinburne University Of Technology & Tafe Divi...,Existing,...,NO DATA,Swinburne University of Technology,https://lh3.googleusercontent.com/-QP2NylEZuhE...,1500,0.000742,1.698581e-08,"POLYGON ((145.03932 -37.82299, 145.03937 -37.8...",817.0,207011520,Hawthorn - South
1,2,BOROONDARA,159\LP5481,203973157,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1501,0.001105,6.526377e-08,"POLYGON ((145.03436 -37.79175, 145.03443 -37.7...",819.0,207011522,Kew - West
2,3,BOROONDARA,3\TP84208,203973089,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1502,0.001003,5.615414e-08,"POLYGON ((145.03480 -37.79127, 145.03487 -37.7...",819.0,207011522,Kew - West
3,4,BOROONDARA,1\TP84208,203973073,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1503,0.001102,6.530917e-08,"POLYGON ((145.03515 -37.79131, 145.03522 -37.7...",819.0,207011522,Kew - West
4,5,BOROONDARA,1\TP802753,203972979,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1504,0.001327,9.438898e-08,"POLYGON ((145.03549 -37.79136, 145.03557 -37.7...",819.0,207011522,Kew - West

In [4]:
joined[["LGA", "PARK_NAME", "SA2_NAME21"]]

,LGA,PARK_NAME,SA2_NAME21
0,BOROONDARA,Swinburne University Of Technology & Tafe Divi...,Hawthorn - South
1,BOROONDARA,Kate Campbell Reserve,Kew - West
2,BOROONDARA,Kate Campbell Reserve,Kew - West
3,BOROONDARA,Kate Campbell Reserve,Kew - West
4,BOROONDARA,Kate Campbell Reserve,Kew - West
...,...,...,...
38805,FRANKSTON,Taverner Square Reserve,Frankston
38806,YARRA,St Kevins College - Waterford,Richmond (South) - Cremorne
38807,FRANKSTON,Seaford Swamp (MWC Drain),Seaford (Vic.)
38808,FRANKSTON,Broughton Reserve,Seaford (Vic.)
38809,FRANKSTON,McCormicks Road Reserve Link,Skye - Sandhurst

In [18]:
joined["OS_CATEGOR"].unique()

array(['Tertiary institutions', 'Parks and gardens',
       'Transport reservations', 'Sportsfields and organised recreation',
       'Recreation corridor', 'Government schools',
       'Natural and semi-natural open space',
       'Services and utilities reserves', 'Non-government schools',
       'Conservation reserves', 'Cemeteries',
       'Civic squares and promenades', 'Public housing reserves'],
      dtype=object)

In [5]:
parks = joined[joined['OS_CATEGOR'].isin(['Parks and gardens', 'Sportsfields and organised recreation'])]

In [6]:
parks.head()

,FID,LGA,VM_PARCEL_,VM_PARCE_1,DATA_SOURC,OS_CATEGOR,OS_CATEG_2,OWNER_TYPE,PARK_NAME,OS_STATUS,...,MANAGER_NA,OWNER_NAME,Image_URL,VPA_ID,SHAPE_Leng,SHAPE_Area,geometry,index_right,SA2_CODE21,SA2_NAME21
1,2,BOROONDARA,159\LP5481,203973157,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1501,0.001105,6.526377e-08,"POLYGON ((145.03436 -37.79175, 145.03443 -37.7...",819.0,207011522,Kew - West
2,3,BOROONDARA,3\TP84208,203973089,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1502,0.001003,5.615414e-08,"POLYGON ((145.03480 -37.79127, 145.03487 -37.7...",819.0,207011522,Kew - West
3,4,BOROONDARA,1\TP84208,203973073,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1503,0.001102,6.530917e-08,"POLYGON ((145.03515 -37.79131, 145.03522 -37.7...",819.0,207011522,Kew - West
4,5,BOROONDARA,1\TP802753,203972979,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1504,0.001327,9.438898e-08,"POLYGON ((145.03549 -37.79136, 145.03557 -37.7...",819.0,207011522,Kew - West
6,7,BOROONDARA,186\LP5481,203971959,VM Parcels,Sportsfields and organised recreation,Not applicable,Local government,Jack Otoole Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-IeXcYfXdodo...,1506,0.001080,5.251028e-08,"POLYGON ((145.03928 -37.79186, 145.03930 -37.7...",819.0,207011522,Kew - West

In [35]:
parks.shape

(11606, 28)

In [34]:
parks[parks["SA2_CODE21"].isnull()]

,FID,LGA,VM_PARCEL_,VM_PARCE_1,DATA_SOURC,OS_CATEGOR,OS_CATEG_2,OWNER_TYPE,PARK_NAME,OS_STATUS,...,MANAGER_NA,OWNER_NAME,Image_URL,VPA_ID,SHAPE_Leng,SHAPE_Area,geometry,index_right,SA2_CODE21,SA2_NAME21
100,101,BOROONDARA,1\TP892794,802526,ARCUE2002,Sportsfields and organised recreation,Not applicable,Local government,Matlock Street Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-IeXcYfXdodo...,1206,0.007932,1.385023e-06,"POLYGON ((145.07327 -37.82805, 145.07321 -37.8...",NaN,NaN,NaN
101,102,BOROONDARA,2068\PP2209,218763952,VM Parcels,Parks and gardens,Regional link,Public authority,Outer Circle Linear Park,Existing,...,NO DATA,VicTrack,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1551,0.006999,7.565784e-07,"POLYGON ((145.05018 -37.79942, 145.05008 -37.7...",NaN,NaN,NaN
105,106,BOROONDARA,58\LP5974,87145,VM Planning,Parks and gardens,Not applicable,Local government,Pitt Street North Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1207,0.002637,2.528166e-07,"POLYGON ((145.06769 -37.86987, 145.06795 -37.8...",NaN,NaN,NaN
119,120,BOROONDARA,1\PS418204,421102836,VM Parcels,Sportsfields and organised recreation,Golf course,Local government,Freeway Golf Course,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-7UfEXUEnrv8...,1910,0.031670,2.721634e-05,"POLYGON ((145.06727 -37.78093, 145.06728 -37.7...",NaN,NaN,NaN
186,187,MANNINGHAM,1\TP903740,211453150,VM Parcels,Sportsfields and organised recreation,Regional link,Local government,KOONUNG CREEK LINEAR PARK,Existing,...,NO DATA,Manningham City Council,https://lh3.googleusercontent.com/-IeXcYfXdodo...,1926,0.009872,3.524004e-06,"POLYGON ((145.15222 -37.79805, 145.15215 -37.7...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38193,38194,DAREBIN,3\LP3091,211446161,ARCUE2002,Sportsfields and organised recreation,Golf course,Local government,Northcote Public Golf Course,Existing,...,NO DATA,Darebin City Council,https://lh3.googleusercontent.com/-7UfEXUEnrv8...,39638,0.012350,6.401722e-06,"POLYGON ((144.98033 -37.75784, 144.98035 -37.7...",NaN,NaN,NaN
38197,38198,DAREBIN,A\LP211948,164634,ARCUE2002,Sportsfields and organised recreation,Golf course,Local government,Northcote Public Golf Course,Existing,...,NO DATA,Darebin City Council,https://lh3.googleusercontent.com/-7UfEXUEnrv8...,39639,0.025312,1.550420e-05,"MULTIPOLYGON (((144.98104 -37.75892, 144.98458...",NaN,NaN,NaN
38203,38204,DAREBIN,RES1\PS337404,27745,ARCUE2002,Sportsfields and organised recreation,Golf course,Local government,Northcote Public Golf Course,Existing,...,NO DATA,Darebin City Council,https://lh3.googleusercontent.com/-7UfEXUEnrv8...,39640,0.006729,1.305551e-06,"POLYGON ((144.98500 -37.76504, 144.98494 -37.7...",NaN,NaN,NaN
38229,38230,DAREBIN,36\LP6671,211198404,ARCUE2002,Sportsfields and organised recreation,Golf course,Local government,Northcote Public Golf Course,Existing,...,NO DATA,Darebin City Council,https://lh3.googleusercontent.com/-7UfEXUEnrv8...,39643,0.002922,3.556700e-07,"POLYGON ((144.98021 -37.75742, 144.98083 -37.7...",NaN,NaN,NaN
38652,38653,FRANKSTON,2058\PP2619,214446241,VM CL Parcels,Sportsfields and organised recreation,Golf course,Crown,Centenary Park Golf Course,Existing,...,NO DATA,Crown,https://lh3.googleusercontent.com/-7UfEXUEnrv8...,39459,0.032721,6.098823e-05,"POLYGON ((145.17268 -38.12784, 145.17287 -38.1...",NaN,NaN,NaN

In [7]:
parks_not_null = parks[parks["SA2_CODE21"].notnull()]

In [8]:
parks_not_null["SA2_CODE21"] = parks_not_null["SA2_CODE21"].astype(int)

/root/anaconda3/lib/python3.11/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [23]:
parks[["LGA", "PARK_NAME", "geometry", "SA2_CODE21", "SA2_NAME21"]]

,LGA,PARK_NAME,geometry,SA2_CODE21,SA2_NAME21
1,BOROONDARA,Kate Campbell Reserve,"POLYGON ((145.03436 -37.79175, 145.03443 -37.7...",207011522,Kew - West
2,BOROONDARA,Kate Campbell Reserve,"POLYGON ((145.03480 -37.79127, 145.03487 -37.7...",207011522,Kew - West
3,BOROONDARA,Kate Campbell Reserve,"POLYGON ((145.03515 -37.79131, 145.03522 -37.7...",207011522,Kew - West
4,BOROONDARA,Kate Campbell Reserve,"POLYGON ((145.03549 -37.79136, 145.03557 -37.7...",207011522,Kew - West
6,BOROONDARA,Jack Otoole Reserve,"POLYGON ((145.03928 -37.79186, 145.03930 -37.7...",207011522,Kew - West
...,...,...,...,...,...
38755,FRANKSTON,Frankston Tennis Club,"POLYGON ((145.12632 -38.15022, 145.12639 -38.1...",214011371,Frankston
38756,FRANKSTON,Frankston Oval,"POLYGON ((145.12153 -38.14768, 145.12127 -38.1...",214011371,Frankston
38763,FRANKSTON,Peninsula Reserve-Douglas Walkway,"POLYGON ((145.14511 -38.14138, 145.14517 -38.1...",214011372,Frankston North
38802,FRANKSTON,Jubilee Park,"POLYGON ((145.14224 -38.15101, 145.14232 -38.1...",214011371,Frankston
38808,FRANKSTON,Broughton Reserve,"POLYGON ((145.12702 -38.10245, 145.12721 -38.1...",214011375,Seaford (Vic.)

In [5]:
# create a JSON 
geoJSON = open_spaces_sf[['FID', 'geometry']].drop_duplicates('FID').to_json()

# print the first 300 chars of the json
print(geoJSON[:300])

In [ ]:
import folium

In [ ]:
_map = folium.Map(location=[-37.020100, 144.964600], tiles="Stamen Terrain", zoom_start=10)

# refer to the folium documentations on how to plot aggregated data.
_map.add_child(folium.Choropleth(
    geo_data=geoJSON,
    name='choropleth',
))

_map

In [9]:
rent_data = pd.read_csv("../data/curated/rental_data_sf.csv")

rent_data.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,SA2_CODE21,SA2_NAME21
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000.0,POINT (144.9696285 -37.8085173),206041503.0,Melbourne CBD - East
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000.0,POINT (144.9693999 -37.8082025),206041503.0,Melbourne CBD - East
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000.0,POINT (144.9602708 -37.8072623),206041504.0,Melbourne CBD - North
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000.0,POINT (144.9592612 -37.8112667),206041504.0,Melbourne CBD - North
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000.0,POINT (144.9586458 -37.8054298),206041506.0,North Melbourne

In [10]:
type(rent_data["geometry"].iloc[1])

str

In [11]:
from shapely import wkt

In [12]:
rent_data['geometry'] = rent_data['geometry'].apply(wkt.loads)

In [13]:
null_rows = rent_data[rent_data['SA2_CODE21'].isnull()]

null_rows.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,SA2_CODE21,SA2_NAME21
9511,1/32 Clarence Street Elsternwick VIC 3185,$370.00,"[0.0, 0.0]",Apartment / Unit / Flat,1 Bed,1 Bath,1 Parking,PLEASE CLICK THE BELOW 'REQUEST AN INSPECTION'...,['AFFORDABLE ELSTERNWICK LIFESTYLE OPPORTUNITY...,"['Intercom', 'Built in wardrobes']",nbn® Hybrid Fibre Coaxial (HFC) is available i...,370.0,3185.0,POINT (0 0),NaN,NaN
9865,1/186 Frankston-Dandenong Road Seaford VIC 3198,$370 / wk,"[0.0, 0.0]",Apartment / Unit / Flat,2 Beds,1 Bath,1 Parking,Unit 1 Now Available - Convenient Location - 2...,"[""This unit is in a quiet complex of 4, with l...","['Built in wardrobes*', 'Heating*']",nbn® Fibre to the Curb (FTTC) is available in ...,370.0,3198.0,POINT (0 0),NaN,NaN
10707,102/1-3 Clare Street Geelong VIC 3220,$340 per week,"[0.0, 0.0]",Apartment / Unit / Flat,1 Bed,1 Bath,− Parking,Furnished apartment in Central Geelong,['Not much will beat this location and the con...,"['Air conditioning', 'Heating', 'Built in ward...",No NBN,340.0,3220.0,POINT (0 0),NaN,NaN
11554,47 Wattle Avenue Wendouree VIC 3355,$340.00 pw,"[0.0, 0.0]",House,2 Beds,1 Bath,2 Parking,FRESH & LOW MAINTENACE TWO BEDROOM HOME IN WEN...,"['BOOK YOUR INSPECTION ONLINE 24/7 Click ""Book...","['Air conditioning', 'Heating', 'Pets Allowed'...",nbn® Fibre to the Node (FTTN) is available in ...,340.0,3355.0,POINT (0 0),NaN,NaN

In [14]:
rent_data_not_null = rent_data[rent_data['SA2_CODE21'].notnull()]

In [15]:
rent_data_not_null.SA2_CODE21 = rent_data_not_null.SA2_CODE21.astype(int)

/tmp/ipykernel_627/1463831701.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rent_data_not_null.SA2_CODE21 = rent_data_not_null.SA2_CODE21.astype(int)

In [16]:
type(rent_data_not_null["geometry"].iloc[1])

shapely.geometry.point.Point

In [17]:
rent_data_geo = gpd.GeoDataFrame(rent_data_not_null, geometry='geometry', crs="EPSG:4326")

In [18]:
rent_data_geo = rent_data_geo.to_crs(epsg=28355)
parks_not_null = parks_not_null.to_crs(epsg=28355)

In [19]:
# Function to get the closest park for a given rental property
def get_closest_park(row):
    # Filter the parks dataframe for the same SA2 district
    parks_same_district = parks_not_null[parks_not_null['SA2_CODE21'] == row['SA2_CODE21']]
    
    # If there are no parks in the same district, return None and a large value
    if parks_same_district.empty:
        return None, None
    
    # Calculate the distance to each park
    distances = parks_same_district['geometry'].distance(row['geometry'])
    
    # Get the index of the park with the minimum distance
    min_distance_idx = distances.idxmin()
    
    # Get the park name and the minimum distance
    closest_park_name = parks_same_district.loc[min_distance_idx, 'PARK_NAME']
    min_distance = distances[min_distance_idx]
    
    return closest_park_name, min_distance

In [20]:
# Apply the function to the rental data
rent_data_geo['closest_park'], rent_data_geo['distance_to_park'] = zip(*rent_data_geo.apply(get_closest_park, axis=1))

In [21]:
rent_data_geo.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,SA2_CODE21,SA2_NAME21,closest_park,distance_to_park
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000.0,POINT (321266.912 5813488.218),206041503,Melbourne CBD - East,Royal Society of Victoria,79.476620
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000.0,POINT (321246.027 5813522.713),206041503,Melbourne CBD - East,Royal Society of Victoria,39.742682
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000.0,POINT (320440.028 5813609.535),206041504,Melbourne CBD - North,Victoria Market Reserve,277.000459
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000.0,POINT (320360.849 5813163.241),206041504,Melbourne CBD - North,Victoria Market Reserve,226.817922
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000.0,POINT (320292.519 5813809.756),206041506,North Melbourne,Courtney Street Reserve,298.491378

In [ ]:
rent_data_geo.to_csv("../data/curated/rental_data_closest_park.csv", index = False)

___________________________________________________________________________________________________________________________________________

Convert the coordinates to GeoPandas Geometry type in shape files

In [7]:
from shapely.geometry import Point
import ast

# Convert the string to a list of floats
rent_data['coordinates'] = rent_data['coordinates'].apply(ast.literal_eval)

# Convert the list of floats to Point geometry (note the order: (longitude, latitude))
rent_data['geometry'] = rent_data['coordinates'].apply(lambda x: Point(x[1], x[0]))


# Save to shapefile
# grent_data.to_file("output_points.shp")

In [8]:
# Convert DataFrame to GeoDataFrame
rent_data_sf = gpd.GeoDataFrame(rent_data, geometry='geometry', crs="EPSG:4326")

rent_data_sf.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000.0,POINT (144.96963 -37.80852)
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000.0,POINT (144.96940 -37.80820)
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000.0,POINT (144.96027 -37.80726)
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000.0,POINT (144.95926 -37.81127)
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000.0,POINT (144.95865 -37.80543)

In [9]:
rent_data_sf = gpd.sjoin(rent_data_sf, sa2_districts_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

rent_data_sf.head()

/root/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):
/tmp/ipykernel_262578/3498390347.py:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: EPSG:7844

  rent_data_sf = gpd.sjoin(rent_data_sf, sa2_districts_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,index_right,SA2_CODE21,SA2_NAME21
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000.0,POINT (144.96963 -37.80852),779.0,206041503,Melbourne CBD - East
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000.0,POINT (144.96940 -37.80820),779.0,206041503,Melbourne CBD - East
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000.0,POINT (144.96027 -37.80726),780.0,206041504,Melbourne CBD - North
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000.0,POINT (144.95926 -37.81127),780.0,206041504,Melbourne CBD - North
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000.0,POINT (144.95865 -37.80543),782.0,206041506,North Melbourne

In [24]:
parks.shape

(11606, 28)

In [11]:
# 1. Group parks by SA2 district and count
park_counts = parks.groupby('SA2_CODE21').size().reset_index(name='num_parks')

# 2. Merge park_counts with rent_data on the SA2 district column
result = pd.merge(rent_data_sf, park_counts, on='SA2_CODE21', how='left')

# Fill NaNs with 0 - in case there are properties with no parks in their SA2 district
result['num_parks'].fillna(0, inplace=True)

print(result[['SA2_CODE21', 'num_parks']])

      SA2_CODE21  num_parks
0      206041503        4.0
1      206041503        4.0
2      206041504        3.0
3      206041504        3.0
4      206041506       24.0
...          ...        ...
11803  213021344       59.0
11804  213011336       30.0
11805  205041096        0.0
11806  210031535       26.0
11807  211031451       28.0

[11808 rows x 2 columns]

In [19]:
# parks['park_area'] = parks['geometry'].area

# 2. Group parks by SA2 district and sum the areas
park_area_sum = parks.groupby('SA2_CODE21')['HA'].sum().reset_index()

# 3. Merge park_area_sum with rent_data on the SA2 district column
result = rent_data_sf.merge(park_area_sum, on='SA2_CODE21', how='left')


# # Fill NaNs with 0 - in case there are properties in SA2 districts with no parks
result['HA'].fillna(0, inplace=True)

print(result[['SA2_CODE21', 'HA']])

      SA2_CODE21       HA
0      206041503   0.5556
1      206041503   0.5556
2      206041504   0.6713
3      206041504   0.6713
4      206041506   8.1177
...          ...      ...
11803  213021344  45.8790
11804  213011336  18.7978
11805  205041096   0.0000
11806  210031535  83.9252
11807  211031451  25.1933

[11808 rows x 2 columns]

In [15]:
print(parks.crs)

EPSG:4326

In [ ]:
# Example: Projecting to UTM zone 33N (just an example, choose appropriate CRS for your region)
parks_projected = parks.to_crs("EPSG:32633")

In [28]:
melb_rent = rent_data_sf[rent_data_sf['SA2_CODE21'].isin(parks["SA2_CODE21"].unique())]

In [29]:
melb_rent.shape

(9328, 17)

In [32]:
parks.head()

,FID,LGA,VM_PARCEL_,VM_PARCE_1,DATA_SOURC,OS_CATEGOR,OS_CATEG_2,OWNER_TYPE,PARK_NAME,OS_STATUS,...,MANAGER_NA,OWNER_NAME,Image_URL,VPA_ID,SHAPE_Leng,SHAPE_Area,geometry,index_right,SA2_CODE21,SA2_NAME21
1,2,BOROONDARA,159\LP5481,203973157,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1501,0.001105,6.526377e-08,"POLYGON ((145.03436 -37.79175, 145.03443 -37.7...",819.0,207011522,Kew - West
2,3,BOROONDARA,3\TP84208,203973089,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1502,0.001003,5.615414e-08,"POLYGON ((145.03480 -37.79127, 145.03487 -37.7...",819.0,207011522,Kew - West
3,4,BOROONDARA,1\TP84208,203973073,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1503,0.001102,6.530917e-08,"POLYGON ((145.03515 -37.79131, 145.03522 -37.7...",819.0,207011522,Kew - West
4,5,BOROONDARA,1\TP802753,203972979,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1504,0.001327,9.438898e-08,"POLYGON ((145.03549 -37.79136, 145.03557 -37.7...",819.0,207011522,Kew - West
6,7,BOROONDARA,186\LP5481,203971959,VM Parcels,Sportsfields and organised recreation,Not applicable,Local government,Jack Otoole Reserve,Existing,...,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-IeXcYfXdodo...,1506,0.001080,5.251028e-08,"POLYGON ((145.03928 -37.79186, 145.03930 -37.7...",819.0,207011522,Kew - West

In [ ]:
parks.groupby()

In [33]:
# Buffer the melb_rent by 5km. Note: Ensure your data is in a CRS that uses meters for distance!
# If not, you might need to reproject your GeoDataFrames to a suitable CRS.
melb_rent_buffered = melb_rent.copy()
melb_rent_buffered['geometry'] = melb_rent_buffered.buffer(5000) 


# Drop 'index_left' and 'index_right' columns if they exist in melb_rent_buffered
if 'index_left' in melb_rent_buffered.columns:
    melb_rent_buffered = melb_rent_buffered.drop(columns='index_left')

if 'index_right' in melb_rent_buffered.columns:
    melb_rent_buffered = melb_rent_buffered.drop(columns='index_right')

# Drop 'index_left' and 'index_right' columns if they exist in parks
if 'index_left' in parks.columns:
    parks = parks.drop(columns='index_left')

if 'index_right' in parks.columns:
    parks = parks.drop(columns='index_right')
    
    
# Perform a spatial join between the buffered melb_rent and parks
test_sdf = gpd.sjoin(melb_rent_buffered, parks, how='left', op='contains')

# Count the number of parks for each entry in melb_rent
parks_count = test_sdf.groupby('index_left').size()

# Add the count back to the melb_rent GeoDataFrame if desired
melb_rent['parks_count'] = parks_count

/tmp/ipykernel_259268/3101853623.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'buffer' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  melb_rent_buffered['geometry'] = melb_rent_buffered.buffer(5000)
/root/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

:

:

In [15]:
# Function to return the index of the nearest open space
def nearest_open_space(point, open_spaces_df):
    distances = open_spaces_df.distance(point)
    return distances.idxmin()

# For each point, find the nearest open space
rent_data_sf['nearest_open_space'] = rent_data_sf['geometry'].apply(lambda point: nearest_open_space(point, joined))

/tmp/ipykernel_259268/34056722.py:3: UserWarning: Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  distances = open_spaces_df.distance(point)

KeyboardInterrupt: