In [1]:
import pandas as pd

In [34]:
sa2_info = pd.read_csv("../data/curated/suburb_info.csv")

In [35]:
sa2_info.shape

(522, 13)

In [36]:
# Accessing all the Victorian Postcodes
post_codes_file_path = "../data/landing/sa2/CG_POSTCODE_2021_SA2_2021.xlsx"
df = pd.read_excel(post_codes_file_path)

vic_df = df.loc[df["POSTCODE"].isin(range(3000,4000))]

# drop the null rows and get all of the SA2 codes
vic_df = vic_df.dropna(subset=["SA2_CODE_2021"])

# sa2_codes = list((vic_df["SA2_CODE_2021"]))
# sa2_codes = list(dict.fromkeys(sa2_codes))
sa2_codes = vic_df['SA2_CODE_2021'].values

sa2_codes = [str(int(x)) for x in sa2_codes if str(x).startswith('2')]
sa2_codes = list(dict.fromkeys(sa2_codes))

# Turn the SA2 codes into integers instead of strings
sa2_codes = [int(x) for x in sa2_codes]

vic_df = vic_df[vic_df["SA2_CODE_2021"].isin(sa2_codes)]

# vic_df = df[df["SA2_CODE_2021"].isin(sa2_info["SA2_codes"].values)]

In [44]:
sa2_codes = sa2_info["SA2_codes"].values

In [45]:
sa2_codes

array([206041506, 206041124, 206041117, 206041503, 206041505, 206041504,
       206041119, 206041510, 206041127, 206051128, 206051512, 206041507,
       206041125, 206051514, 206051511, 206041508, 206041509, 206041118,
       213031348, 213031351, 213031350, 213021343, 213011338, 213031347,
       213031352, 213021344, 213021346, 213021341, 213021342, 213011570,
       213011332, 213011328, 213011336, 213011337, 213011333, 213011335,
       213011334, 213011569, 213041359, 213041360, 213041461, 213041462,
       213011329, 213041463, 213051582, 213051468, 213051589, 213051579,
       213051590, 213051363, 213051587, 213021345, 213051467, 213051584,
       213051586, 213051585, 213051361, 213051362, 213051588, 213051583,
       213051581, 213051580, 213051368, 213051466, 213051464, 206031113,
       206041120, 206031115, 206041121, 213031349, 210011534, 210011226,
       210011228, 210011533, 210051248, 213011340, 213011331, 213011339,
       213041575, 206031116, 206031501, 210011230, 206031502, 210011231,
       210011227, 210051245, 210031439, 210051250, 210031236, 206011498,
       210031537, 206011109, 210031538, 210031440, 210031536, 210031535,
       210051243, 210051242, 210051247, 206071140, 206011107, 206011496,
       206011495, 206011106, 209021526, 209021429, 206011497, 210051246,
       210031237, 210051544, 210051445, 210041240, 209041225, 210051441,
       210051542, 210051442, 210051543, 210051545, 210051443, 206071142,
       206071143, 206071141, 206071145, 206071139, 206021112, 206021110,
       206021500, 206021499, 209021525, 209021428, 209021524, 209021523,
       209041223, 209041530, 209041221, 209041529, 209041432, 209041433,
       209041431, 209011199, 209011201, 209011200, 209041220, 209011204,
       209041217, 209041216, 209021205, 209011196, 209011203, 209011198,
       209011197, 209011202, 209031213, 209031215, 209031210, 209031209,
       209031214, 209031212, 207011154, 207011521, 207011522, 207011148,
       207011147, 207021157, 207021156, 207031164, 207021159, 207021160,
       207021425, 211021261, 207021424, 211021262, 211031268, 211031265,
       211051275, 206071518, 206071517, 207011152, 207011519, 207011520,
       207011150, 207011149, 207011155, 207031165, 212051319, 207031167,
       207031163, 211041269, 207031162, 207031161, 211041271, 211041270,
       211041272, 211041273, 211031267, 211031266, 211031452, 211031451,
       211031450, 211051280, 211031263, 211051277, 211051281, 212011289,
       211051286, 211051283, 211051285, 211051278, 206061516, 206061515,
       206061138, 208041194, 206061136, 206061135, 208021177, 208041195,
       207011146, 212051326, 212051323, 212051324, 212051327, 212051322,
       212051321, 207031166, 211011254, 211011446, 211011251, 211011259,
       211011260, 211011449, 211051274, 211011257, 211051284, 212021453,
       211011255, 211011447, 211011448, 211051282, 208021178, 208021182,
       208021181, 208021176, 208021427, 208021426, 208021180, 212041309,
       212051325, 212051567, 212051568, 212041313, 212041310, 212041317,
       208031184, 212041460, 212041318, 212041566, 212041565, 212041316,
       212041459, 212031562, 212041564, 212041563, 212041312, 212021295,
       211011258, 211011256, 206051134, 206051513, 206051129, 208021179,
       208011172, 208011170, 208011169, 208021174, 208011171, 208011173,
       208031191, 208031188, 208011168, 208031190, 208031192, 208031189,
       208031183, 208031193, 208031187, 208031186, 208031185, 214011375,
       214011372, 214011373, 214011371, 214011370, 206051130, 203021043,
       203011035, 203011034, 203021047, 203021486, 203021488, 203021040,
       203021485, 203021037, 203021487, 203021042, 203011036, 203031053,
       203031489, 203021039, 203021045, 203021046, 203021044, 203031052,
       203031490, 203031048, 203031051, 203031049, 217031476, 217031473,
       217031475, 217031474, 217031472, 217031471, 217041477, 215011387,
       217011423, 217041478, 217041480, 217041479, 217011420, 217011421,
       217011422, 215011393, 215011392, 201031015, 201021012, 213041574,
       210041539, 210021232, 213041577, 213041576, 213041358, 213041573,
       213041572, 213041571, 213041578, 201021009, 213041353, 201011005,
       201011484, 201011481, 201011002, 201011483, 201011482, 201011001,
       201011006, 201031014, 201011007, 201021010, 201031013, 201011008,
       201021011, 202021028, 201031017, 215011386, 215011391, 215011394,
       215011389, 215011390, 215031400, 215011388, 210041540, 210041541,
       210021235, 210021234, 202021030, 204011060, 210021233, 202021031,
       202021026, 202021029, 202021027, 202031033, 201031016, 215021398,
       215021399, 215021395, 215021396, 215021470, 215021469, 215031405,
       216011410, 204011058, 215031401, 215031403, 202011024, 202011025,
       202011021, 202011020, 202011018, 202011019, 202031032, 202011023,
       202011022, 216011409, 216011407, 216011408, 216011406, 215031402,
       215031404, 216031419, 204011055, 216031415, 216031418, 216031594,
       216031416, 216031593, 216021413, 216021411, 216021412, 204011062,
       209041224, 204011056, 204011059, 204011054, 204021064, 204021063,
       204021067, 204011057, 204021066, 204021065, 204031070, 204031491,
       204031073, 204031492, 204031072, 204031069, 204031075, 205021082,
       205021080, 205051099, 204011061, 216021414, 204031071, 204031068,
       209041437, 209041532, 209041435, 209041436, 209041528, 209041531,
       209041527, 209031211, 211051276, 211051279, 212021297, 212021454,
       212021299, 212021455, 212021293, 212021554, 212031457, 212021456,
       212031458, 212021553, 212011546, 212011548, 212011550, 212011547,
       212011551, 212011549, 212011552, 205011076, 205011079, 205011077,
       205011078, 205041095, 205051101, 205041098, 205031090, 205041096,
       205041094, 205051104, 205051102, 205041493, 205041494, 205051103,
       205051100, 205021086, 205031087, 205021081, 205021083, 205021084,
       205021085, 214011374, 214021385, 212031308, 214021379, 214021378,
       205031088, 205031091, 205031093, 214021381, 214021592, 214021591,
       214021382, 214021384, 214021377, 214021383, 205031089, 205031092,
       212031306, 212031561, 212031558, 212031303, 212031560, 212031559,
       214011376, 212031557, 212031300, 212031304, 212031555, 212031556])

In [36]:
vic_df.head()

,POSTCODE,SA2_CODE_2021,SA2_NAME_2021,RATIO_FROM_TO,INDIV_TO_REGION_QLTY_INDICATOR,OVERALL_QUALITY_INDICATOR,BMOS_NULL_FLAG
1948,3000.0,206041506,North Melbourne,0.002426,Good,Poor,1
1949,3000.0,206041124,Parkville,0.005243,Good,Poor,1
1950,3000.0,206041117,Carlton,0.013905,Good,Poor,0
1951,3000.0,206041503,Melbourne CBD - East,0.227238,Poor,Poor,0
1952,3000.0,206041505,Melbourne CBD - West,0.361512,Poor,Poor,0

In [37]:
vic_df.POSTCODE = vic_df.POSTCODE.astype(int)

In [38]:
vic_df.head()

,POSTCODE,SA2_CODE_2021,SA2_NAME_2021,RATIO_FROM_TO,INDIV_TO_REGION_QLTY_INDICATOR,OVERALL_QUALITY_INDICATOR,BMOS_NULL_FLAG
1948,3000,206041506,North Melbourne,0.002426,Good,Poor,1
1949,3000,206041124,Parkville,0.005243,Good,Poor,1
1950,3000,206041117,Carlton,0.013905,Good,Poor,0
1951,3000,206041503,Melbourne CBD - East,0.227238,Poor,Poor,0
1952,3000,206041505,Melbourne CBD - West,0.361512,Poor,Poor,0

In [39]:
occurences = vic_df.groupby(["POSTCODE"]).size()

In [40]:
occurences.loc[occurences > 1]

POSTCODE
3000    6
3003    3
3004    6
3006    4
3008    4
       ..
3981    3
3984    3
3987    2
3988    3
3996    3
Length: 441, dtype: int64

In [41]:
sa2_occurences = vic_df.groupby(["SA2_NAME_2021"]).size()

In [42]:
sa2_occurences.loc[sa2_occurences > 1]

SA2_NAME_2021
Airport West                   2
Albert Park                    2
Alexandra                      9
Alfredton                      2
Alphington - Fairfield         2
                              ..
Yallourn North - Glengarry     5
Yarra Valley                   5
Yarram                         9
Yarriambiack                  18
Yea                            6
Length: 341, dtype: int64

In [2]:
postcodes_df = pd.read_csv("../data/landing/sa2/postcodes.csv")

In [3]:
postcodes_df.head()

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,MMM_2019,ced,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating
0,230,200,ANU,ACT,149.11900,-35.277700,NaN,NaN,Updated 3-Dec-2022,NaN,...,1.0,NaN,NaN,N2,NaN,NaN,Unincorporated ACT,89399.0,Durack,NaN
1,21820,200,Australian National University,ACT,149.11890,-35.277700,NaN,NaN,Updated 3-Dec-2022,NaN,...,1.0,NaN,NaN,N2,NaN,NaN,Unincorporated ACT,89399.0,Durack,NaN
2,232,800,DARWIN,NT,130.83668,-12.458684,NaN,NaN,Updated 3-Dec-2022,70101.0,...,2.0,NaN,NaN,NT1,PHN701,Northern Territory,Darwin Waterfront Precinct,71150.0,Solomon,Inner Metropolitan
3,24049,800,DARWIN CITY,NT,130.83668,-12.458684,NaN,NaN,Updated 3-Dec-2022,70101.0,...,2.0,NaN,NaN,NT1,PHN701,Northern Territory,Darwin Waterfront Precinct,71150.0,Solomon,Inner Metropolitan
4,233,801,DARWIN,NT,130.83668,-12.458684,NaN,NaN,Updated 3-Dec-2022,70101.0,...,2.0,NaN,NaN,NT1,PHN701,NaN,Darwin Waterfront Precinct,71150.0,Lingiari,Rural

In [8]:
postcodes_df = postcodes_df.dropna(subset=["SA2_MAINCODE_2016"])
postcodes_df.SA2_MAINCODE_2016 = postcodes_df.SA2_MAINCODE_2016.astype(int)

In [20]:
postcodes_df.to_csv("../data/raw/postcodes.csv", index=False)

In [49]:
postcodes_df = pd.read_csv("../data/raw/postcodes.csv")

In [50]:
postcodes_df[postcodes_df["state"] == "VIC"]

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,MMM_2019,ced,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating
6182,4746,3000,MELBOURNE,VIC,144.956776,-37.817403,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,15.244751,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan
6183,4747,3001,MELBOURNE,VIC,144.956776,-37.817403,CITY MAIL PROCESSING CENTRE,Post Office Boxes,Updated 25-Mar-2020 SA3,20605.0,...,1.0,Melbourne,15.244751,V1,PHN203,NaN,Melbourne,24600.0,Maribyrnong,NaN
6184,4748,3002,EAST MELBOURNE,VIC,144.982207,-37.818517,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,14.315022,V1,PHN201,North Western Melbourne,Yarra,27350.0,Melbourne,Inner Metropolitan
6185,4749,3003,WEST MELBOURNE,VIC,144.949592,-37.810871,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,15.316063,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan
6186,4750,3004,MELBOURNE,VIC,144.970161,-37.844246,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20605.0,...,1.0,Macnamara,-3492.000000,V1,PHN203,South Eastern Melbourne,Port Phillip,25900.0,Macnamara,Inner Metropolitan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18488,11312,8120,MELBOURNE,VIC,144.970161,-37.844246,MELBOURNE GPO,LVR,Updated 25-Mar-2020 SA3,20605.0,...,1.0,NaN,NaN,V1,PHN203,NaN,Port Phillip,25900.0,Macnamara,NaN
18489,11313,8205,MELBOURNE,VIC,144.970161,-37.844246,MELBOURNE GPO,LVR,Updated 25-Mar-2020 SA3,20605.0,...,1.0,NaN,NaN,V1,PHN203,NaN,Port Phillip,25900.0,Macnamara,NaN
18490,11331,8785,DANDENONG,VIC,145.208504,-38.016114,DANDENONG DC,Post Office Boxes,Updated 2-Dec-2022,21204.0,...,1.0,NaN,15.138582,V1,PHN203,NaN,Greater Dandenong,22670.0,Isaacs,NaN
18491,24132,8785,DANDENONG SOUTH,VIC,145.208504,-38.016114,NaN,LVR,Updated 2-Dec-2022,21204.0,...,1.0,NaN,NaN,NaN,NaN,NaN,Greater Dandenong,22670.0,NaN,NaN
18503,23878,9999,NORTH POLE,VIC,144.956776,-37.817403,CITY DELIVERY CENTRE,Delivery Area,Added 1-July-2021,20604.0,...,1.0,Melbourne,15.244751,NaN,NaN,NaN,Melbourne,24600.0,Macnamara,NaN

In [51]:
vic_postcodes = postcodes_df[postcodes_df["state"] == "VIC"]

In [52]:
vic_postcodes[["postcode", "locality", "SA2_MAINCODE_2016"]]

       postcode         locality  SA2_MAINCODE_2016
6182       3000        MELBOURNE          206041122
6183       3001        MELBOURNE          206041122
6184       3002   EAST MELBOURNE          206041119
6185       3003   WEST MELBOURNE          206041127
6186       3004        MELBOURNE          206041126
...         ...              ...                ...
18488      8120        MELBOURNE          206041122
18489      8205        MELBOURNE          206041122
18490      8785        DANDENONG          212041311
18491      8785  DANDENONG SOUTH          212041311
18503      9999       NORTH POLE          206041122

[3537 rows x 3 columns]

In [31]:
vic_postcodes.head()

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,MMM_2019,ced,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating
6182,4746,3000,MELBOURNE,VIC,144.956776,-37.817403,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,15.244751,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan
6183,4747,3001,MELBOURNE,VIC,144.956776,-37.817403,CITY MAIL PROCESSING CENTRE,Post Office Boxes,Updated 25-Mar-2020 SA3,20605.0,...,1.0,Melbourne,15.244751,V1,PHN203,NaN,Melbourne,24600.0,Maribyrnong,NaN
6184,4748,3002,EAST MELBOURNE,VIC,144.982207,-37.818517,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,14.315022,V1,PHN201,North Western Melbourne,Yarra,27350.0,Melbourne,Inner Metropolitan
6185,4749,3003,WEST MELBOURNE,VIC,144.949592,-37.810871,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,15.316063,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan
6186,4750,3004,MELBOURNE,VIC,144.970161,-37.844246,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20605.0,...,1.0,Macnamara,-3492.000000,V1,PHN203,South Eastern Melbourne,Port Phillip,25900.0,Macnamara,Inner Metropolitan

In [40]:
vic_postcodes = vic_postcodes.loc[vic_postcodes["postcode"].isin(range(3000,4000))]

In [41]:
vic_postcodes.head()

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,MMM_2019,ced,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating
6182,4746,3000,MELBOURNE,VIC,144.956776,-37.817403,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,15.244751,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan
6183,4747,3001,MELBOURNE,VIC,144.956776,-37.817403,CITY MAIL PROCESSING CENTRE,Post Office Boxes,Updated 25-Mar-2020 SA3,20605.0,...,1.0,Melbourne,15.244751,V1,PHN203,NaN,Melbourne,24600.0,Maribyrnong,NaN
6184,4748,3002,EAST MELBOURNE,VIC,144.982207,-37.818517,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,14.315022,V1,PHN201,North Western Melbourne,Yarra,27350.0,Melbourne,Inner Metropolitan
6185,4749,3003,WEST MELBOURNE,VIC,144.949592,-37.810871,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,15.316063,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan
6186,4750,3004,MELBOURNE,VIC,144.970161,-37.844246,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20605.0,...,1.0,Macnamara,-3492.000000,V1,PHN203,South Eastern Melbourne,Port Phillip,25900.0,Macnamara,Inner Metropolitan

In [48]:
vic_postcodes[["postcode", "locality", "SA2_MAINCODE_2016"]]

      postcode                 locality  SA2_MAINCODE_2016
6184      3002           EAST MELBOURNE          206041119
6185      3003           WEST MELBOURNE          206041127
6187      3004    ST KILDA ROAD CENTRAL          206041125
6188      3004  ST KILDA ROAD MELBOURNE          206041125
6189      3005       WORLD TRADE CENTRE          206041118
...        ...                      ...                ...
9694      3995              WATTLE BANK          205031093
9695      3995                WONTHAGGI          205031093
9696      3995                 WOOLAMAI          205031093
9697      3996                INVERLOCH          205031093
9698      3996              POUND CREEK          205031087

[3312 rows x 3 columns]

In [43]:
sa2_codes

[206041506,
 206041124,
 206041117,
 206041503,
 206041505,
 206041504,
 206041119,
 206041510,
 206041127,
 206051128,
 206051512,
 206041507,
 206041125,
 206051514,
 206051511,
 206041508,
 206041509,
 206041118,
 213031348,
 213031351,
 213031350,
 213021343,
 213011338,
 213031347,
 213031352,
 213021344,
 213021346,
 213021341,
 213021342,
 213011570,
 213011332,
 213011328,
 213011336,
 213011337,
 213011333,
 213011335,
 213011334,
 213011569,
 213041359,
 213041360,
 213041461,
 213041462,
 213011329,
 213041463,
 213051582,
 213051468,
 213051589,
 213051579,
 213051590,
 213051363,
 213051587,
 213021345,
 213051467,
 213051584,
 213051586,
 213051585,
 213051361,
 213051362,
 213051588,
 213051583,
 213051581,
 213051580,
 213051368,
 213051466,
 213051464,
 206031113,
 206041120,
 206031115,
 206041121,
 213031349,
 210011534,
 210011226,
 210011228,
 210011533,
 210051248,
 213011340,
 213011331,
 213011339,
 213041575,
 206031116,
 206031501,
 210011230,
 206031502,
 210011231,
 210011227,
 210051245,
 210031439,
 210051250,
 210031236,
 206011498,
 210031537,
 206011109,
 210031538,
 210031440,
 210031536,
 210031535,
 210051243,
 210051242,
 210051247,
 206071140,
 206011107,
 206011496,
 206011495,
 206011106,
 209021526,
 209021429,
 206011497,
 210051246,
 210031237,
 210051544,
 210051445,
 210041240,
 209041225,
 210051441,
 210051542,
 210051442,
 210051543,
 210051545,
 210051443,
 206071142,
 206071143,
 206071141,
 206071145,
 206071139,
 206021112,
 206021110,
 206021500,
 206021499,
 209021525,
 209021428,
 209021524,
 209021523,
 209041223,
 209041530,
 209041221,
 209041529,
 209041432,
 209041433,
 209041431,
 209011199,
 209011201,
 209011200,
 209041220,
 209011204,
 209041217,
 209041216,
 209021205,
 209011196,
 209011203,
 209011198,
 209011197,
 209011202,
 209031213,
 209031215,
 209031210,
 209031209,
 209031214,
 209031212,
 207011154,
 207011521,
 207011522,
 207011148,
 207011147,
 207021157,
 207021156,
 207031164,
 207021159,
 207021160,
 207021425,
 211021261,
 207021424,
 211021262,
 211031268,
 211031265,
 211051275,
 206071518,
 206071517,
 207011152,
 207011519,
 207011520,
 207011150,
 207011149,
 207011155,
 207031165,
 212051319,
 207031167,
 207031163,
 211041269,
 207031162,
 207031161,
 211041271,
 211041270,
 211041272,
 211041273,
 211031267,
 211031266,
 211031452,
 211031451,
 211031450,
 211051280,
 211031263,
 211051277,
 211051281,
 212011289,
 211051286,
 211051283,
 211051285,
 211051278,
 206061516,
 206061515,
 206061138,
 208041194,
 206061136,
 206061135,
 208021177,
 208041195,
 207011146,
 212051326,
 212051323,
 212051324,
 212051327,
 212051322,
 212051321,
 207031166,
 211011254,
 211011446,
 211011251,
 211011259,
 211011260,
 211011449,
 211051274,
 211011257,
 211051284,
 212021453,
 211011255,
 211011447,
 211011448,
 211051282,
 208021178,
 208021182,
 208021181,
 208021176,
 208021427,
 208021426,
 208021180,
 212041309,
 212051325,
 212051567,
 212051568,
 212041313,
 212041310,
 212041317,
 208031184,
 212041460,
 212041318,
 212041566,
 212041565,
 212041316,
 212041459,
 212031562,
 212041564,
 212041563,
 212041312,
 212021295,
 211011258,
 211011256,
 206051134,
 206051513,
 206051129,
 208021179,
 208011172,
 208011170,
 208011169,
 208021174,
 208011171,
 208011173,
 208031191,
 208031188,
 208011168,
 208031190,
 208031192,
 208031189,
 208031183,
 208031193,
 208031187,
 208031186,
 208031185,
 214011375,
 214011372,
 214011373,
 214011371,
 214011370,
 206051130,
 203021043,
 203011035,
 203011034,
 203021047,
 203021486,
 203021488,
 203021040,
 203021485,
 203021037,
 203021487,
 203021042,
 203011036,
 203031053,
 203031489,
 203021039,
 203021045,
 203021046,
 203021044,
 203031052,
 203031490,
 203031048,
 203031051,
 203031049,
 217031476,
 217031473,
 217031475,
 217031474,
 217031472,
 217031471,
 217041477,
 215011387,
 217011423,
 217041478,
 217041480,
 217041479,
 217011420,
 217011421,
 217011422,
 215011393,
 215011392,
 201031015,
 201021012,
 213041574,
 210041539,
 210021232,
 213041577,
 213041576,
 213041358,
 213041573,
 213041572,
 213041571,
 213041578,
 201021009,
 213041353,
 201011005,
 201011484,
 201011481,
 201011002,
 201011483,
 201011482,
 201011001,
 201011006,
 201031014,
 201011007,
 201021010,
 201031013,
 201011008,
 201021011,
 202021028,
 201031017,
 215011386,
 215011391,
 215011394,
 215011389,
 215011390,
 215031400,
 215011388,
 210041540,
 210041541,
 210021235,
 210021234,
 202021030,
 204011060,
 210021233,
 202021031,
 202021026,
 202021029,
 202021027,
 202031033,
 201031016,
 215021398,
 215021399,
 215021395,
 215021396,
 215021470,
 215021469,
 215031405,
 216011410,
 204011058,
 215031401,
 215031403,
 202011024,
 202011025,
 202011021,
 202011020,
 202011018,
 202011019,
 202031032,
 202011023,
 202011022,
 216011409,
 216011407,
 216011408,
 216011406,
 215031402,
 215031404,
 216031419,
 204011055,
 216031415,
 216031418,
 216031594,
 216031416,
 216031593,
 216021413,
 216021411,
 216021412,
 204011062,
 209041224,
 204011056,
 204011059,
 204011054,
 204021064,
 204021063,
 204021067,
 204011057,
 204021066,
 204021065,
 204031070,
 204031491,
 204031073,
 204031492,
 204031072,
 204031069,
 204031075,
 205021082,
 205021080,
 205051099,
 204011061,
 216021414,
 204031071,
 204031068,
 209041437,
 209041532,
 209041435,
 209041436,
 209041528,
 209041531,
 209041527,
 209031211,
 211051276,
 211051279,
 212021297,
 212021454,
 212021299,
 212021455,
 212021293,
 212021554,
 212031457,
 212021456,
 212031458,
 212021553,
 212011546,
 212011548,
 212011550,
 212011547,
 212011551,
 212011549,
 212011552,
 205011076,
 205011079,
 205011077,
 205011078,
 205041095,
 205051101,
 205041098,
 205031090,
 205041096,
 205041094,
 205051104,
 205051102,
 205041493,
 205041494,
 205051103,
 205051100,
 205021086,
 205031087,
 205021081,
 205021083,
 205021084,
 205021085,
 214011374,
 214021385,
 212031308,
 214021379,
 214021378,
 205031088,
 205031091,
 205031093,
 214021381,
 214021592,
 214021591,
 214021382,
 214021384,
 214021377,
 214021383,
 205031089,
 205031092,
 212031306,
 212031561,
 212031558,
 212031303,
 212031560,
 212031559,
 214011376,
 212031557,
 212031300,
 212031304,
 212031555,
 212031556]

In [46]:
vic_postcodes = vic_postcodes.loc[vic_postcodes["SA2_MAINCODE_2016"].isin(sa2_codes)]

In [47]:
vic_postcodes.head()

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,MMM_2019,ced,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating
6184,4748,3002,EAST MELBOURNE,VIC,144.982207,-37.818517,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,14.315022,V1,PHN201,North Western Melbourne,Yarra,27350.0,Melbourne,Inner Metropolitan
6185,4749,3003,WEST MELBOURNE,VIC,144.949592,-37.810871,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,15.316063,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan
6187,4751,3004,ST KILDA ROAD CENTRAL,VIC,144.970161,-37.844246,Melbourne Metro,NaN,Updated 6-Feb-2020,20605.0,...,1.0,Macnamara,-3492.000000,V1,PHN203,South Eastern Melbourne,Port Phillip,25900.0,Macnamara,Inner Metropolitan
6188,22851,3004,ST KILDA ROAD MELBOURNE,VIC,144.976000,-37.836800,Melbourne Metro,NaN,Updated 25-Jan-2020,20605.0,...,1.0,Macnamara,-3492.000000,V1,PHN203,South Eastern Melbourne,Port Phillip,25900.0,Macnamara,Inner Metropolitan
6189,4752,3005,WORLD TRADE CENTRE,VIC,144.950858,-37.824608,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,1.0,Melbourne,NaN,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,NaN

In [19]:
vic_postcodes["postcode"].unique()

array([3002, 3003, 3004, 3005, 3008, 3010, 3011, 3012, 3013, 3015, 3016,
       3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3028,
       3029, 3030, 3031, 3032, 3033, 3036, 3037, 3038, 3039, 3040, 3041,
       3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3052, 3053,
       3054, 3055, 3057, 3058, 3059, 3060, 3061, 3063, 3064, 3065, 3066,
       3067, 3068, 3071, 3072, 3073, 3074, 3076, 3078, 3079, 3081, 3082,
       3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3093, 3094,
       3095, 3096, 3097, 3099, 3102, 3103, 3104, 3105, 3106, 3107, 3108,
       3109, 3111, 3113, 3114, 3115, 3116, 3122, 3123, 3124, 3125, 3126,
       3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137,
       3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148,
       3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3158, 3159, 3160,
       3161, 3162, 3163, 3165, 3166, 3167, 3169, 3170, 3171, 3172, 3174,
       3175, 3176, 3177, 3178, 3179, 3180, 3181, 3183, 3184, 3185, 3186,
       3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197,
       3198, 3199, 3200, 3201, 3202, 3204, 3206, 3207, 3211, 3212, 3213,
       3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225,
       3228, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239,
       3240, 3241, 3242, 3243, 3249, 3250, 3251, 3254, 3260, 3264, 3265,
       3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276,
       3277, 3278, 3279, 3280, 3281, 3282, 3283, 3284, 3285, 3286, 3287,
       3289, 3292, 3293, 3294, 3300, 3301, 3302, 3303, 3304, 3305, 3309,
       3310, 3311, 3312, 3314, 3315, 3317, 3318, 3319, 3321, 3322, 3323,
       3324, 3325, 3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336,
       3337, 3340, 3341, 3342, 3345, 3350, 3351, 3352, 3353, 3354, 3355,
       3356, 3357, 3358, 3360, 3361, 3363, 3364, 3370, 3371, 3373, 3374,
       3375, 3377, 3378, 3379, 3380, 3381, 3384, 3385, 3387, 3388, 3390,
       3391, 3392, 3393, 3395, 3396, 3399, 3400, 3401, 3402, 3407, 3409,
       3412, 3413, 3414, 3415, 3418, 3419, 3420, 3423, 3424, 3428, 3429,
       3430, 3431, 3432, 3433, 3434, 3435, 3437, 3438, 3440, 3441, 3442,
       3444, 3446, 3447, 3448, 3450, 3451, 3453, 3458, 3460, 3461, 3462,
       3463, 3464, 3465, 3467, 3468, 3469, 3472, 3475, 3477, 3478, 3480,
       3482, 3483, 3485, 3487, 3488, 3489, 3490, 3491, 3494, 3496, 3498,
       3500, 3501, 3502, 3505, 3506, 3507, 3509, 3512, 3515, 3516, 3517,
       3518, 3520, 3521, 3522, 3523, 3525, 3527, 3529, 3530, 3531, 3533,
       3537, 3540, 3542, 3544, 3546, 3549, 3550, 3551, 3552, 3554, 3555,
       3556, 3557, 3558, 3559, 3561, 3562, 3563, 3564, 3565, 3566, 3567,
       3568, 3570, 3571, 3572, 3573, 3575, 3576, 3579, 3580, 3581, 3583,
       3584, 3585, 3586, 3588, 3589, 3590, 3591, 3594, 3595, 3596, 3597,
       3599, 3607, 3608, 3610, 3612, 3614, 3616, 3617, 3618, 3619, 3620,
       3621, 3622, 3623, 3624, 3629, 3630, 3631, 3633, 3634, 3635, 3636,
       3637, 3638, 3639, 3640, 3641, 3643, 3644, 3646, 3647, 3649, 3658,
       3659, 3660, 3661, 3662, 3663, 3664, 3665, 3666, 3669, 3670, 3671,
       3672, 3673, 3675, 3676, 3677, 3678, 3682, 3683, 3685, 3687, 3688,
       3690, 3691, 3695, 3697, 3698, 3699, 3700, 3701, 3704, 3705, 3707,
       3708, 3709, 3711, 3712, 3713, 3714, 3715, 3717, 3718, 3719, 3720,
       3722, 3723, 3724, 3725, 3726, 3727, 3728, 3730, 3732, 3733, 3735,
       3736, 3737, 3738, 3739, 3740, 3741, 3744, 3746, 3747, 3749, 3750,
       3751, 3752, 3753, 3754, 3755, 3756, 3757, 3758, 3759, 3760, 3761,
       3762, 3763, 3764, 3765, 3766, 3767, 3770, 3775, 3777, 3778, 3779,
       3781, 3782, 3783, 3785, 3786, 3787, 3788, 3789, 3791, 3792, 3793,
       3795, 3796, 3797, 3799, 3802, 3803, 3804, 3805, 3806, 3808, 3810,
       3816, 3818, 3820, 3821, 3822, 3823, 3824, 3825, 3831, 3832, 3833,
       3835, 3840, 3841, 3842, 3844, 3847, 3850, 3851, 3852, 3853, 3854,
       3856, 3857, 3858, 3859, 3860, 3862, 3864, 3865, 3869, 3870, 3871,
       3873, 3874, 3875, 3878, 3880, 3882, 3885, 3886, 3887, 3888, 3889,
       3890, 3891, 3892, 3893, 3895, 3896, 3898, 3900, 3902, 3903, 3904,
       3909, 3910, 3911, 3912, 3913, 3915, 3916, 3918, 3919, 3920, 3921,
       3922, 3923, 3925, 3926, 3927, 3928, 3929, 3930, 3933, 3934, 3936,
       3937, 3938, 3939, 3940, 3941, 3942, 3943, 3944, 3945, 3946, 3950,
       3951, 3953, 3954, 3956, 3957, 3958, 3959, 3960, 3962, 3964, 3965,
       3966, 3967, 3971, 3975, 3977, 3978, 3979, 3980, 3984, 3987, 3988,
       3990, 3991, 3992, 3995, 3996])

In [30]:
vic_postcodes.columns

Index(['id', 'postcode', 'locality', 'state', 'long', 'lat', 'dc', 'type',
       'status', 'sa3', 'sa3name', 'sa4', 'sa4name', 'region', 'Lat_precise',
       'Long_precise', 'SA1_MAINCODE_2011', 'SA1_MAINCODE_2016',
       'SA2_MAINCODE_2016', 'SA2_NAME_2016', 'SA3_CODE_2016', 'SA3_NAME_2016',
       'SA4_CODE_2016', 'SA4_NAME_2016', 'RA_2011', 'RA_2016', 'MMM_2015',
       'MMM_2019', 'ced', 'altitude', 'chargezone', 'phn_code', 'phn_name',
       'lgaregion', 'lgacode', 'electorate', 'electoraterating'],
      dtype='object')

In [63]:
vic_postcodes[vic_postcodes["postcode"] == 3888][["postcode", "SA2_MAINCODE_2016"]]

      postcode  SA2_MAINCODE_2016
9368      3888          205021085
9369      3888          205021085
9370      3888          205021085
9371      3888          205021085
9372      3888          205021085
9373      3888          205021085
9374      3888          205021085
9375      3888          205021085
9376      3888          205021085
9377      3888          205021085
9378      3888          205021085
9379      3888          205021085
9380      3888          205021085
9381      3888          205021085
9382      3888          205021085
9383      3888          205021085
9384      3888          205021085
9386      3888          205021085
9387      3888          205021082
9388      3888          205021085
9389      3888          205021085
9390      3888          205021085
9391      3888          205021085
9392      3888          205021085
9393      3888          205021085

Try joining spatially

In [67]:
import geopandas as gpd

sa2_sf = gpd.read_file("../data/landing/sa2/SA2_2021_AUST_GDA2020.shp")

In [68]:
sa2_sf = sa2_sf.loc[sa2_sf["STE_NAME21"] == "Victoria"]

Change all SA2 codes such that it starts with a 2

In [57]:
vic_postcodes = vic_postcodes[vic_postcodes['SA2_MAINCODE_2016'].astype(str).str.startswith('2')]

In [61]:
from shapely.geometry import Point
import ast

vic_postcodes['geometry'] = [Point(xy) for xy in zip(vic_postcodes['long'], vic_postcodes['lat'])]

In [62]:
vic_postcodes.head()

,id,postcode,locality,state,long,lat,dc,type,status,sa3,...,ced,altitude,chargezone,phn_code,phn_name,lgaregion,lgacode,electorate,electoraterating,geometry
6182,4746,3000,MELBOURNE,VIC,144.956776,-37.817403,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,Melbourne,15.244751,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan,POINT (144.956776 -37.817403)
6183,4747,3001,MELBOURNE,VIC,144.956776,-37.817403,CITY MAIL PROCESSING CENTRE,Post Office Boxes,Updated 25-Mar-2020 SA3,20605.0,...,Melbourne,15.244751,V1,PHN203,NaN,Melbourne,24600.0,Maribyrnong,NaN,POINT (144.956776 -37.817403)
6184,4748,3002,EAST MELBOURNE,VIC,144.982207,-37.818517,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,Melbourne,14.315022,V1,PHN201,North Western Melbourne,Yarra,27350.0,Melbourne,Inner Metropolitan,POINT (144.982207 -37.818517)
6185,4749,3003,WEST MELBOURNE,VIC,144.949592,-37.810871,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20604.0,...,Melbourne,15.316063,V1,PHN201,North Western Melbourne,Melbourne,24600.0,Melbourne,Inner Metropolitan,POINT (144.949592 -37.810871)
6186,4750,3004,MELBOURNE,VIC,144.970161,-37.844246,CITY DELIVERY CENTRE,Delivery Area,Updated 6-Feb-2020,20605.0,...,Macnamara,-3492.000000,V1,PHN203,South Eastern Melbourne,Port Phillip,25900.0,Macnamara,Inner Metropolitan,POINT (144.970161 -37.844246)

In [64]:
vic_postcodes_restricted = vic_postcodes[["id", "postcode", "locality", "state", "long", "lat", "geometry"]]

In [72]:
vic_postcodes_sf = gpd.GeoDataFrame(vic_postcodes_restricted, geometry='geometry', crs="EPSG:4326")

In [73]:
vic_postcodes_sf = gpd.sjoin(vic_postcodes_sf, sa2_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

/root/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):
/tmp/ipykernel_631/2750430260.py:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: EPSG:7844

  vic_postcodes_sf = gpd.sjoin(vic_postcodes_sf, sa2_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

In [74]:
vic_postcodes_sf = vic_postcodes_sf.drop(columns='index_right')
vic_postcodes_sf.head()

,id,postcode,locality,state,long,lat,geometry,SA2_CODE21,SA2_NAME21
6182,4746,3000,MELBOURNE,VIC,144.956776,-37.817403,POINT (144.95678 -37.81740),206041505,Melbourne CBD - West
6183,4747,3001,MELBOURNE,VIC,144.956776,-37.817403,POINT (144.95678 -37.81740),206041505,Melbourne CBD - West
6184,4748,3002,EAST MELBOURNE,VIC,144.982207,-37.818517,POINT (144.98221 -37.81852),206041119,East Melbourne
6185,4749,3003,WEST MELBOURNE,VIC,144.949592,-37.810871,POINT (144.94959 -37.81087),206041510,West Melbourne - Residential
6186,4750,3004,MELBOURNE,VIC,144.970161,-37.844246,POINT (144.97016 -37.84425),206051128,Albert Park

In [76]:

print(len(sa2_codes), len(vic_postcodes_sf["SA2_CODE21"].unique()))

522 355

In [77]:
sa2_sf.head()

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
644,201011001,Alfredton,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,52.7109,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5..."
645,201011002,Ballarat,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,12.3787,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5..."
646,201011005,Buninyong,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,51.5855,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6..."
647,201011006,Delacombe,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,34.1607,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5..."
648,201011007,Smythes Creek,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,104.7274,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6..."

Test add to new csv file

In [26]:
postcodes = vic_postcodes["postcode"].unique()


cols = ["Estimated resident population (no.)",
        "Employed (no.)", "Unemployed (no.)",
        'Median equivalised total household income (weekly) ($)',
        'Land area (ha)', 'Median weekly household rental payment ($)', 
        'Average family size (no. of persons)', 'Total families (no.)', 'Total dwellings (no.)']

postcodes_info = (pd.DataFrame(columns= cols, index=postcodes)).rename_axis('Postcode', axis=1)

In [27]:
postcodes_info.head()

Postcode,Estimated resident population (no.),Employed (no.),Unemployed (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN