In [77]:
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

In [78]:
data = pd.read_csv("../data/curated/merged_data.csv")
print(list(data.columns))

['name', 'coordinates', 'property type', 'beds', 'baths', 'parking', 'property features', 'nbn', 'weekly rent amount', 'postcode', 'geometry', 'sa2_code21', 'sa2_name21', 'closest primary school', 'distance primary school', 'closest secondary school', 'distance secondary school', 'closest university campus', 'distance university campus', 'closest hospital', 'distance to closest hospital', 'offence count 2023', 'offence count 2022', 'offence count 2021', 'estimated resident population (no.) 2011', 'employed (no.) 2011', 'unemployed (no.) 2011', 'in the labour force (no.) 2011', 'total persons aged 15 years and over (no.) 2011', 'land area (ha) 2011', 'total families (no.) 2011', 'total dwellings (no.) 2011', 'median equivalised total household income (weekly) ($) 2011', 'median weekly household rental payment ($) 2011', 'average family size (no. of persons) 2011', 'estimated resident population (no.) 2016', 'employed (no.) 2016', 'unemployed (no.) 2016', 'in the labour force (no.) 2016', 'total persons aged 15 years and over (no.) 2016', 'land area (ha) 2016', 'total families (no.) 2016', 'total dwellings (no.) 2016', 'median equivalised total household income (weekly) ($) 2016', 'median weekly household rental payment ($) 2016', 'average family size (no. of persons) 2016', 'estimated resident population (no.) 2021', 'employed (no.) 2021', 'unemployed (no.) 2021', 'in the labour force (no.) 2021', 'total persons aged 15 years and over (no.) 2021', 'land area (ha) 2021', 'total families (no.) 2021', 'total dwellings (no.) 2021', 'median equivalised total household income (weekly) ($) 2021', 'median weekly household rental payment ($) 2021', 'average family size (no. of persons) 2021', 'total_supermarkets', 'major_supermarkets', 'city_centre', 'closest_city_centre', 'coastal', 'closest_cc_dist', 'dist_to_melb']

In [79]:
# remove column with just 0
dropped_columns_list = []
for col_name in data.columns:
    if (data[col_name] == 0).all():
        dropped_columns_list.append(col_name)
        data = data.drop(col_name, axis=1)
print(dropped_columns_list)
print(list(data.columns))

['estimated resident population (no.) 2011', 'land area (ha) 2011', 'total dwellings (no.) 2011', 'estimated resident population (no.) 2016', 'land area (ha) 2016', 'total dwellings (no.) 2016']
['name', 'coordinates', 'property type', 'beds', 'baths', 'parking', 'property features', 'nbn', 'weekly rent amount', 'postcode', 'geometry', 'sa2_code21', 'sa2_name21', 'closest primary school', 'distance primary school', 'closest secondary school', 'distance secondary school', 'closest university campus', 'distance university campus', 'closest hospital', 'distance to closest hospital', 'offence count 2023', 'offence count 2022', 'offence count 2021', 'employed (no.) 2011', 'unemployed (no.) 2011', 'in the labour force (no.) 2011', 'total persons aged 15 years and over (no.) 2011', 'total families (no.) 2011', 'median equivalised total household income (weekly) ($) 2011', 'median weekly household rental payment ($) 2011', 'average family size (no. of persons) 2011', 'employed (no.) 2016', 'unemployed (no.) 2016', 'in the labour force (no.) 2016', 'total persons aged 15 years and over (no.) 2016', 'total families (no.) 2016', 'median equivalised total household income (weekly) ($) 2016', 'median weekly household rental payment ($) 2016', 'average family size (no. of persons) 2016', 'estimated resident population (no.) 2021', 'employed (no.) 2021', 'unemployed (no.) 2021', 'in the labour force (no.) 2021', 'total persons aged 15 years and over (no.) 2021', 'land area (ha) 2021', 'total families (no.) 2021', 'total dwellings (no.) 2021', 'median equivalised total household income (weekly) ($) 2021', 'median weekly household rental payment ($) 2021', 'average family size (no. of persons) 2021', 'total_supermarkets', 'major_supermarkets', 'city_centre', 'closest_city_centre', 'coastal', 'closest_cc_dist', 'dist_to_melb']

In [80]:
def predict_2023_value(y_values, col_name): 
    """ Function predicts 2023 value of variable given past data. Assumes linear relationship"""
    # 0, 5, 10 represents 2011, 2016, 2021
    x_values = [0,5,10]
    print(y_values)
    print(col_name)
    model = LinearRegression()
    x_values = np.array(x_values).reshape(-1,1)
    y_values = np.array(y_values).reshape(-1,1)
    model.fit(x_values, y_values)
    # 12 represents 2023
    predict_2023 = model.predict(np.array(12).reshape(-1,1))
    return pd.Series({col_name: predict_2023[0][0]})

In [81]:

# predict median equivalised total household income (weekly) ($) 2023
median_income_2023_column = data.apply(lambda x:
    predict_2023_value([x["median equivalised total household income (weekly) ($) 2011"], 
     x["median equivalised total household income (weekly) ($) 2016"],
     x["median equivalised total household income (weekly) ($) 2021"]], 
    "predicted median equivalised total household income (weekly) ($) 2023"), axis=1)

data = pd.concat([data, median_income_2023_column], axis=1)
data[["median equivalised total household income (weekly) ($) 2011", 
     "median equivalised total household income (weekly) ($) 2016",
     "median equivalised total household income (weekly) ($) 2021", 
     "predicted median equivalised total household income (weekly) ($) 2023"]]

data = data.drop(["median equivalised total household income (weekly) ($) 2011", 
     "median equivalised total household income (weekly) ($) 2016",
     "median equivalised total household income (weekly) ($) 2021"], axis=1)

[1089.0, 1265.6666666666667, 1495.0]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[628.0, 761.0, 931.0]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[575.25, 651.25, 812.75]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[1201.0, 1361.0, 1578.5]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[658.0, 745.0, 909.0]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[574.75, 624.5, 737.75]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[616.25, 734.0, 976.25]
predicted median equivalised total household income (weekly) ($) 2023
[579.0, 646.0, 819.0]
predicted median equivalised total household income (weekly) ($) 2023
[766.0, 878.0, 1065.0]
predicted median equivalised total household income (weekly) ($) 2023
[560.0, 670.0, 795.0]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[616.25, 734.0, 976.25]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[674.6666666666666, 829.0, 1104.0]
predicted median equivalised total household income (weekly) ($) 2023
[710.25, 895.5, 1230.75]
predicted median equivalised total household income (weekly) ($) 2023
[798.5, 894.5, 1124.5]
predicted median equivalised total household income (weekly) ($) 2023
[588.0, 661.0, 794.0]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[710.25, 895.5, 1230.75]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[756.5, 871.5, 1086.5]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[766.0, 878.0, 1065.0]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[588.5, 674.0, 846.5]
predicted median equivalised total household income (weekly) ($) 2023
[742.5, 839.0, 998.5]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[545.0, 635.0, 726.0]
predicted median equivalised total household income (weekly) ($) 2023
[1299.3333333333333, 1442.0, 1709.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[579.0, 646.0, 819.0]
predicted median equivalised total household income (weekly) ($) 2023
[830.0, 1021.0, 1395.0]
predicted median equivalised total household income (weekly) ($) 2023
[852.0, 1006.0, 1315.0]
predicted median equivalised total household income (weekly) ($) 2023
[556.0, 659.0, 834.0]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[560.0, 670.0, 795.0]
predicted median equivalised total household income (weekly) ($) 2023
[629.0, 689.0, 845.0]
predicted median equivalised total household income (weekly) ($) 2023
[575.25, 651.25, 812.75]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[575.25, 651.25, 812.75]
predicted median equivalised total household income (weekly) ($) 2023
[516.0, 610.0, 681.0]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[510.0, 571.0, 735.0]
predicted median equivalised total household income (weekly) ($) 2023
[510.0, 571.0, 735.0]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[689.3333333333334, 797.0, 990.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[658.0, 745.0, 909.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[679.25, 779.5, 954.875]
predicted median equivalised total household income (weekly) ($) 2023
[811.5, 972.0, 1216.0]
predicted median equivalised total household income (weekly) ($) 2023
[708.0, 811.0, 1090.0]
predicted median equivalised total household income (weekly) ($) 2023
[665.5, 761.5, 937.0]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[673.25, 768.5, 954.0]
predicted median equivalised total household income (weekly) ($) 2023
[852.0, 980.5, 1216.0]
predicted median equivalised total household income (weekly) ($) 2023
[616.5, 703.5, 856.5]
predicted median equivalised total household income (weekly) ($) 2023
[565.0, 634.0, 779.0]
predicted median equivalised total household income (weekly) ($) 2023
[830.0, 1021.0, 1395.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[729.5, 859.0, 1116.25]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[738.6666666666666, 847.3333333333334, 996.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[629.0, 689.0, 845.0]
predicted median equivalised total household income (weekly) ($) 2023
[697.0, 813.0, 1045.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[588.0, 643.0, 790.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[772.5, 857.5, 1033.5]
predicted median equivalised total household income (weekly) ($) 2023
[593.0, 681.0, 815.0]
predicted median equivalised total household income (weekly) ($) 2023
[797.5, 951.5, 1236.0]
predicted median equivalised total household income (weekly) ($) 2023
[657.0, 751.0, 954.0]
predicted median equivalised total household income (weekly) ($) 2023
[1201.0, 1361.0, 1578.5]
predicted median equivalised total household income (weekly) ($) 2023
[565.0, 634.0, 779.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[797.4, 849.2, 1072.7]
predicted median equivalised total household income (weekly) ($) 2023
[738.6666666666666, 847.3333333333334, 996.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[679.25, 779.5, 954.875]
predicted median equivalised total household income (weekly) ($) 2023
[566.0, 647.0, 790.0]
predicted median equivalised total household income (weekly) ($) 2023
[563.75, 657.0, 866.0]
predicted median equivalised total household income (weekly) ($) 2023
[811.5, 972.0, 1216.0]
predicted median equivalised total household income (weekly) ($) 2023
[797.4, 849.2, 1072.7]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[1201.0, 1361.0, 1578.5]
predicted median equivalised total household income (weekly) ($) 2023
[643.3333333333334, 782.5, 1049.1666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[534.0, 608.0, 752.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.0, 691.0, 840.0]
predicted median equivalised total household income (weekly) ($) 2023
[667.0, 723.0, 907.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[1058.0, 1231.0, 1487.0]
predicted median equivalised total household income (weekly) ($) 2023
[932.5714285714286, 968.2857142857144, 1175.428571428571]
predicted median equivalised total household income (weekly) ($) 2023
[1051.0, 1216.5, 1521.5]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[511.0, 576.0, 675.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[665.5, 756.5, 935.0]
predicted median equivalised total household income (weekly) ($) 2023
[689.3333333333334, 797.0, 990.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[697.6, 758.2, 988.8]
predicted median equivalised total household income (weekly) ($) 2023
[545.0, 635.0, 726.0]
predicted median equivalised total household income (weekly) ($) 2023
[545.0, 635.0, 726.0]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[609.0, 697.0, 833.0]
predicted median equivalised total household income (weekly) ($) 2023
[830.0, 1021.0, 1395.0]
predicted median equivalised total household income (weekly) ($) 2023
[1051.0, 1216.5, 1521.5]
predicted median equivalised total household income (weekly) ($) 2023
[679.25, 779.5, 954.875]
predicted median equivalised total household income (weekly) ($) 2023
[679.25, 779.5, 954.875]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[639.0, 719.0, 898.0]
predicted median equivalised total household income (weekly) ($) 2023
[639.0, 719.0, 898.0]
predicted median equivalised total household income (weekly) ($) 2023
[571.0, 631.0, 772.0]
predicted median equivalised total household income (weekly) ($) 2023
[738.6666666666666, 847.3333333333334, 996.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[718.0, 807.0, 1062.0]
predicted median equivalised total household income (weekly) ($) 2023
[1299.3333333333333, 1442.0, 1709.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[680.0, 763.0, 919.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[554.0, 632.0, 726.0]
predicted median equivalised total household income (weekly) ($) 2023
[901.2, 1035.6, 1273.6]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[543.0, 666.0, 834.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[663.5, 768.5, 940.0]
predicted median equivalised total household income (weekly) ($) 2023
[863.3333333333334, 979.3333333333334, 1344.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[1051.0, 1216.5, 1521.5]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[852.0, 1006.0, 1315.0]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[663.5, 768.5, 940.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[663.5, 768.5, 940.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 959.0, 1210.0]
predicted median equivalised total household income (weekly) ($) 2023
[516.0, 610.0, 681.0]
predicted median equivalised total household income (weekly) ($) 2023
[665.5, 761.5, 937.0]
predicted median equivalised total household income (weekly) ($) 2023
[616.5, 703.5, 856.5]
predicted median equivalised total household income (weekly) ($) 2023
[624.0, 721.0, 881.0]
predicted median equivalised total household income (weekly) ($) 2023
[593.0, 681.0, 815.0]
predicted median equivalised total household income (weekly) ($) 2023
[477.0, 517.5, 618.0]
predicted median equivalised total household income (weekly) ($) 2023
[572.3333333333334, 647.6666666666666, 783.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[749.6666666666666, 908.0, 1161.0]
predicted median equivalised total household income (weekly) ($) 2023
[966.0, 1164.0, 1510.0]
predicted median equivalised total household income (weekly) ($) 2023
[775.0, 852.5, 1056.5]
predicted median equivalised total household income (weekly) ($) 2023
[863.3333333333334, 979.3333333333334, 1344.6666666666667]
predicted median equivalised total household income (weekly) ($) 2023
[738.5, 828.5, 975.5]
predicted median equivalised total household income (weekly) ($) 2023
[542.0, 624.0, 774.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[1051.0, 1216.5, 1521.5]
predicted median equivalised total household income (weekly) ($) 2023
[572.3333333333334, 647.6666666666666, 783.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[1244.3333333333333, 1357.6666666666667, 1612.0]
predicted median equivalised total household income (weekly) ($) 2023
[616.5, 703.5, 856.5]
predicted median equivalised total household income (weekly) ($) 2023
[621.0, 737.0, 882.0]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.0, 691.0, 840.0]
predicted median equivalised total household income (weekly) ($) 2023
[522.0, 588.0, 782.0]
predicted median equivalised total household income (weekly) ($) 2023
[710.25, 895.5, 1230.75]
predicted median equivalised total household income (weekly) ($) 2023
[689.3333333333334, 797.0, 990.6666666666666]
predicted median equivalised total household income (weekly) ($) 2023
[591.0, 691.0, 840.0]
predicted median equivalised total household income (weekly) ($) 2023
[741.5, 831.5, 1026.5]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[550.0, 660.0, 829.0]
predicted median equivalised total household income (weekly) ($) 2023
[510.0, 571.0, 735.0]
predicted median equivalised total household income (weekly) ($) 2023
[509.0, 560.0, 637.0]
predicted median equivalised total household income (weekly) ($) 2023
[573.5, 669.5, 850.5]
predicted median equivalised total household income (weekly) ($) 2023
[543.0, 666.0, 834.0]
predicted median equivalised total household income (weekly) ($) 2023
[653.0, 758.0, 887.0]
predicted median equivalised total household income (weekly) ($) 2023
[555.0, 619.0, 729.0]
predicted median equivalised total household income (weekly) ($) 2023
[674.6666666666666, 829.0, 1104.0]
predicted median equivalised total household income (weekly) ($) 2023
[591.6666666666666, 655.0, 942.3333333333334]
predicted median equivalised total household income (weekly) ($) 2023
[915.0, 1258.0, 1693.0]
predicted median equivalised total household income (weekly) ($) 2023
[1086.0, 1222.3333333333333, 1488.0]
predicted median equivalised total household income (weekly) ($) 2023
[800.5, 876.5, 1295.0]
predicted median equivalised total household income (weekly) ($) 2023
[650.0, 726.6666666666666, 868.0]

In [82]:
# employed (no.) 2023
employee_2023_column = data.apply(lambda x:
    predict_2023_value([x["employed (no.) 2011"], 
     x["employed (no.) 2016"],
     x["employed (no.) 2021"]], 
    "employed (no.) 2023"), axis=1)

data = pd.concat([data, employee_2023_column], axis=1)

"""
data = data.drop(["employed (no.) 2011", 
     "employed (no.) 2016",
     "employed (no.) 2021"], axis=1)
"""

data[["employed (no.) 2011", 
     "employed (no.) 2016",
     "employed (no.) 2021", 
     "employed (no.) 2023"]]

[20267.0, 19917.0, 20755.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[3626.0, 4667.0, 5832.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[21428.0, 23213.0, 25584.0]
employed (no.) 2023
[18779.0, 20516.0, 22520.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[18317.0, 20163.0, 21172.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[9336.0, 9768.0, 10931.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[23464.0, 23844.0, 24538.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[19737.0, 21663.0, 24555.0]
employed (no.) 2023
[1501.0, 1599.0, 1793.0]
employed (no.) 2023
[8615.0, 8810.0, 9479.0]
employed (no.) 2023
[5424.0, 5418.0, 5578.0]
employed (no.) 2023
[18779.0, 20516.0, 22520.0]
employed (no.) 2023
[18779.0, 20516.0, 22520.0]
employed (no.) 2023
[19737.0, 21663.0, 24555.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[18223.0, 20650.0, 24053.0]
employed (no.) 2023
[20402.0, 24274.0, 27593.0]
employed (no.) 2023
[13377.0, 13622.0, 14552.0]
employed (no.) 2023
[3624.0, 3409.0, 3701.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[20402.0, 24274.0, 27593.0]
employed (no.) 2023
[18779.0, 20516.0, 22520.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[9781.0, 10371.0, 11104.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[8615.0, 8810.0, 9479.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[7603.0, 8208.0, 10532.0]
employed (no.) 2023
[15386.0, 14597.0, 14268.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[2380.0, 2365.0, 2558.0]
employed (no.) 2023
[12359.0, 15872.0, 17560.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[1501.0, 1599.0, 1793.0]
employed (no.) 2023
[10635.0, 13263.0, 15204.0]
employed (no.) 2023
[7455.0, 8876.0, 12382.0]
employed (no.) 2023
[2006.0, 2001.0, 2151.0]
employed (no.) 2023
[18779.0, 20516.0, 22520.0]
employed (no.) 2023
[18779.0, 20516.0, 22520.0]
employed (no.) 2023
[5424.0, 5418.0, 5578.0]
employed (no.) 2023
[4651.0, 4402.0, 4671.0]
employed (no.) 2023
[21428.0, 23213.0, 25584.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[21428.0, 23213.0, 25584.0]
employed (no.) 2023
[1521.0, 1523.0, 1475.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[2725.0, 2483.0, 2656.0]
employed (no.) 2023
[2725.0, 2483.0, 2656.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[9336.0, 9768.0, 10931.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[11660.0, 11606.0, 12646.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[10885.0, 11215.0, 12497.0]
employed (no.) 2023
[2747.0, 2809.0, 3371.0]
employed (no.) 2023
[15318.0, 15781.0, 17500.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[21166.0, 21972.0, 24745.0]
employed (no.) 2023
[3542.0, 7052.0, 10654.0]
employed (no.) 2023
[13617.0, 13752.0, 15444.0]
employed (no.) 2023
[4313.0, 3992.0, 4437.0]
employed (no.) 2023
[10635.0, 13263.0, 15204.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[16890.0, 18193.0, 20682.0]
employed (no.) 2023
[4651.0, 4402.0, 4671.0]
employed (no.) 2023
[21319.0, 22153.0, 25761.0]
employed (no.) 2023
[11660.0, 11606.0, 12646.0]
employed (no.) 2023
[3936.0, 4049.0, 5536.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[26190.0, 27234.0, 28261.0]
employed (no.) 2023
[3275.0, 3246.0, 3383.0]
employed (no.) 2023
[13183.0, 13870.0, 16327.0]
employed (no.) 2023
[4296.0, 4357.0, 4779.0]
employed (no.) 2023
[18317.0, 20163.0, 21172.0]
employed (no.) 2023
[4313.0, 3992.0, 4437.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[34512.0, 44004.0, 67201.0]
employed (no.) 2023
[16890.0, 18193.0, 20682.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[1398.0, 1301.0, 1270.0]
employed (no.) 2023
[16460.0, 18715.0, 20261.0]
employed (no.) 2023
[10885.0, 11215.0, 12497.0]
employed (no.) 2023
[34512.0, 44004.0, 67201.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[18317.0, 20163.0, 21172.0]
employed (no.) 2023
[22684.0, 26682.0, 31754.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[2852.0, 2879.0, 2910.0]
employed (no.) 2023
[7787.0, 7863.0, 8934.0]
employed (no.) 2023
[5143.0, 5683.0, 7564.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[9743.0, 10148.0, 11672.0]
employed (no.) 2023
[34892.0, 42653.0, 57187.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[11660.0, 11606.0, 12646.0]
employed (no.) 2023
[1558.0, 1450.0, 1469.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[12410.0, 12262.0, 13768.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[18779.0, 20516.0, 22520.0]
employed (no.) 2023
[2380.0, 2365.0, 2558.0]
employed (no.) 2023
[2380.0, 2365.0, 2558.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[11660.0, 11606.0, 12646.0]
employed (no.) 2023
[7999.0, 8201.0, 9108.0]
employed (no.) 2023
[10635.0, 13263.0, 15204.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[7395.0, 7368.0, 7987.0]
employed (no.) 2023
[7395.0, 7368.0, 7987.0]
employed (no.) 2023
[2588.0, 2617.0, 2888.0]
employed (no.) 2023
[16890.0, 18193.0, 20682.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[12359.0, 15872.0, 17560.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[3356.0, 3432.0, 3869.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[1632.0, 1669.0, 2092.0]
employed (no.) 2023
[37526.0, 37990.0, 40575.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[2304.0, 2453.0, 2695.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[11286.0, 10995.0, 12165.0]
employed (no.) 2023
[18995.0, 22084.0, 26436.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[7455.0, 8876.0, 12382.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[11286.0, 10995.0, 12165.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[11286.0, 10995.0, 12165.0]
employed (no.) 2023
[5546.0, 6026.0, 6710.0]
employed (no.) 2023
[1521.0, 1523.0, 1475.0]
employed (no.) 2023
[15318.0, 15781.0, 17500.0]
employed (no.) 2023
[13617.0, 13752.0, 15444.0]
employed (no.) 2023
[4368.0, 4373.0, 4725.0]
employed (no.) 2023
[3275.0, 3246.0, 3383.0]
employed (no.) 2023
[4504.0, 4429.0, 4760.0]
employed (no.) 2023
[10915.0, 11299.0, 12794.0]
employed (no.) 2023
[11448.0, 14696.0, 24103.0]
employed (no.) 2023
[17922.0, 21766.0, 25109.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[18995.0, 22084.0, 26436.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[10915.0, 11299.0, 12794.0]
employed (no.) 2023
[9580.0, 13249.0, 19206.0]
employed (no.) 2023
[13617.0, 13752.0, 15444.0]
employed (no.) 2023
[6290.0, 6423.0, 7163.0]
employed (no.) 2023
[11660.0, 11606.0, 12646.0]
employed (no.) 2023
[7787.0, 7863.0, 8934.0]
employed (no.) 2023
[7554.0, 8097.0, 9421.0]
employed (no.) 2023
[20402.0, 24274.0, 27593.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[7787.0, 7863.0, 8934.0]
employed (no.) 2023
[16066.0, 16443.0, 18125.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[2004.0, 2042.0, 2275.0]
employed (no.) 2023
[2725.0, 2483.0, 2656.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[2304.0, 2453.0, 2695.0]
employed (no.) 2023
[6230.0, 6154.0, 6565.0]
employed (no.) 2023
[1980.0, 2087.0, 2431.0]
employed (no.) 2023
[18223.0, 20650.0, 24053.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[3320.0, 4715.0, 5889.0]
employed (no.) 2023
[26005.0, 27433.0, 29511.0]
employed (no.) 2023
[10712.0, 11552.0, 13879.0]
employed (no.) 2023
[11660.0, 11606.0, 12646.0]
employed (no.) 2023
[6230.0, 6154.0, 6565.0]
employed (no.) 2023
[13183.0, 13870.0, 16327.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[1261.0, 1208.0, 1348.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[16890.0, 18193.0, 20682.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[22684.0, 26682.0, 31754.0]
employed (no.) 2023
[22684.0, 26682.0, 31754.0]
employed (no.) 2023
[21428.0, 23213.0, 25584.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[16890.0, 18193.0, 20682.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[21166.0, 21972.0, 24745.0]
employed (no.) 2023
[21166.0, 21972.0, 24745.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[3275.0, 3246.0, 3383.0]
employed (no.) 2023
[3936.0, 4049.0, 5536.0]
employed (no.) 2023
[18779.0, 20516.0, 22520.0]
employed (no.) 2023
[20402.0, 24274.0, 27593.0]
employed (no.) 2023
[19040.0, 20714.0, 21857.0]
employed (no.) 2023
[4124.0, 4671.0, 5616.0]
employed (no.) 2023
[12359.0, 15872.0, 17560.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[13617.0, 13752.0, 15444.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[19737.0, 21663.0, 24555.0]
employed (no.) 2023
[2174.0, 2377.0, 3485.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[12419.0, 14360.0, 15036.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[10712.0, 11552.0, 13879.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[3081.0, 2874.0, 3014.0]
employed (no.) 2023
[16540.0, 16313.0, 17455.0]
employed (no.) 2023
[4504.0, 4429.0, 4760.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[29457.0, 32942.0, 37265.0]
employed (no.) 2023
[16890.0, 18193.0, 20682.0]
employed (no.) 2023
[23404.0, 25836.0, 29312.0]
employed (no.) 2023
[7554.0, 8097.0, 9421.0]
employed (no.) 2023
[4651.0, 4402.0, 4671.0]
employed (no.) 2023
[11286.0, 10995.0, 12165.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[7787.0, 7863.0, 8934.0]
employed (no.) 2023
[9277.0, 10012.0, 10956.0]
employed (no.) 2023
[14172.0, 14813.0, 16492.0]
employed (no.) 2023
[9130.0, 8832.0, 10363.0]
employed (no.) 2023
[5545.0, 5888.0, 7246.0]
employed (no.) 2023
[7395.0, 7368.0, 7987.0]
employed (no.) 2023
[10885.0, 11215.0, 12497.0]
employed (no.) 2023
[11660.0, 11606.0, 12646.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[7395.0, 7368.0, 7987.0]
employed (no.) 2023
[9321.0, 9705.0, 11470.0]
employed (no.) 2023
[2718.0, 2647.0, 2957.0]
employed (no.) 2023
[6060.0, 5784.0, 6403.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[10635.0, 13263.0, 15204.0]
employed (no.) 2023
[7603.0, 8208.0, 10532.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[26005.0, 27433.0, 29511.0]
employed (no.) 2023
[14975.0, 15088.0, 16421.0]
employed (no.) 2023
[3320.0, 4715.0, 5889.0]
employed (no.) 2023
[19737.0, 21663.0, 24555.0]
employed (no.) 2023
[2658.0, 3288.0, 5205.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[5106.0, 5045.0, 5130.0]
employed (no.) 2023
[11921.0, 11910.0, 13414.0]
employed (no.) 2023
[5547.0, 6193.0, 7135.0]
employed (no.) 2023
[8785.0, 8303.0, 8833.0]
employed (no.) 2023
[24012.0, 25295.0, 26254.0]
employed (no.) 2023
[15318.0, 15781.0, 17500.0]
employed (no.) 2023
[10635.0, 13263.0, 15204.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[25316.0, 28076.0, 38130.0]
employed (no.) 2023
[24969.0, 29153.0, 33682.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[5545.0, 5888.0, 7246.0]
employed (no.) 2023
[7603.0, 8208.0, 10532.0]
employed (no.) 2023
[3526.0, 3457.0, 3919.0]
employed (no.) 2023
[36404.0, 50771.0, 68651.0]
employed (no.) 2023
[55833.0, 67942.0, 88622.0]
employed (no.) 2023
[4124.0, 4671.0, 5616.0]
employed (no.) 2023
[3526.0, 3457.0, 3919.0]
employed (no.) 2023
[21428.0, 23213.0, 25584.0]
employed (no.) 2023
[12047.0, 12446.0, 16382.0]
employed (no.) 2023
[7603.0, 8208.0, 10532.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[16460.0, 18715.0, 20261.0]
employed (no.) 2023
[9130.0, 8832.0, 10363.0]
employed (no.) 2023
[16066.0, 16443.0, 18125.0]
employed (no.) 2023
[2597.0, 2457.0, 2687.0]
employed (no.) 2023
[2597.0, 2457.0, 2687.0]
employed (no.) 2023
[21428.0, 23213.0, 25584.0]
employed (no.) 2023
[21428.0, 23213.0, 25584.0]
employed (no.) 2023
[9130.0, 8832.0, 10363.0]
employed (no.) 2023
[10635.0, 13263.0, 15204.0]
employed (no.) 2023
[12410.0, 12262.0, 13768.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[15831.0, 17042.0, 20270.0]
employed (no.) 2023
[11286.0, 10995.0, 12165.0]
employed (no.) 2023
[7603.0, 8208.0, 10532.0]
employed (no.) 2023
[7603.0, 8208.0, 10532.0]
employed (no.) 2023
[1501.0, 1599.0, 1793.0]
employed (no.) 2023
[11286.0, 10995.0, 12165.0]
employed (no.) 2023
[2006.0, 2001.0, 2151.0]
employed (no.) 2023
[22684.0, 26682.0, 31754.0]
employed (no.) 2023
[3526.0, 3457.0, 3919.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[7603.0, 8208.0, 10532.0]
employed (no.) 2023
[22684.0, 26682.0, 31754.0]
employed (no.) 2023
[21319.0, 22153.0, 25761.0]
employed (no.) 2023
[4651.0, 4402.0, 4671.0]
employed (no.) 2023
[2852.0, 2879.0, 2910.0]
employed (no.) 2023
[15318.0, 15781.0, 17500.0]
employed (no.) 2023
[1578.0, 1499.0, 2169.0]
employed (no.) 2023
[1575.0, 1766.0, 2047.0]
employed (no.) 2023
[4564.0, 4579.0, 4966.0]
employed (no.) 2023
[3532.0, 3703.0, 5044.0]
employed (no.) 2023
[2725.0, 2483.0, 2656.0]
employed (no.) 2023
[976.0, 1240.0, 2907.0]
employed (no.) 2023
[5865.0, 6062.0, 6450.0]
employed (no.) 2023
[9130.0, 8832.0, 10363.0]
employed (no.) 2023
[3542.0, 7052.0, 10654.0]
employed (no.) 2023
[3081.0, 2874.0, 3014.0]
employed (no.) 2023
[10915.0, 11299.0, 12794.0]
employed (no.) 2023
[11660.0, 11606.0, 12646.0]
employed (no.) 2023
[13617.0, 13752.0, 15444.0]
employed (no.) 2023
[1980.0, 2087.0, 2431.0]
employed (no.) 2023
[4296.0, 4357.0, 4779.0]
employed (no.) 2023
[24331.0, 27259.0, 32047.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[16626.0, 17871.0, 20947.0]
employed (no.) 2023
[16890.0, 18193.0, 20682.0]
employed (no.) 2023
[9130.0, 8832.0, 10363.0]
employed (no.) 2023
[26045.0, 26240.0, 28494.0]
employed (no.) 2023
[18995.0, 22084.0, 26436.0]
employed (no.) 2023
[3615.0, 3681.0, 4318.0]
employed (no.) 2023
[21319.0, 22153.0, 25761.0]
employed (no.) 2023
[13617.0, 13752.0, 15444.0]
employed (no.) 2023
[3526.0, 3457.0, 3919.0]
employed (no.) 2023
[9336.0, 9768.0, 10931.0]
employed (no.) 2023
[7724.0, 8351.0, 10836.0]
employed (no.) 2023
[24012.0, 25295.0, 26254.0]
employed (no.) 2023
[20402.0, 24274.0, 27593.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[18317.0, 20163.0, 21172.0]
employed (no.) 2023
[20402.0, 24274.0, 27593.0]
employed (no.) 2023
[7424.0, 8057.0, 8901.0]
employed (no.) 2023
[12505.0, 15721.0, 21564.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[7554.0, 8097.0, 9421.0]
employed (no.) 2023
[2004.0, 2042.0, 2275.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[12359.0, 15872.0, 17560.0]
employed (no.) 2023
[1854.0, 1850.0, 1906.0]
employed (no.) 2023
[5099.0, 4860.0, 5145.0]
employed (no.) 2023
[3467.0, 3821.0, 4381.0]
employed (no.) 2023
[37526.0, 37990.0, 40575.0]
employed (no.) 2023
[10885.0, 11215.0, 12497.0]
employed (no.) 2023
[24969.0, 29153.0, 33682.0]
employed (no.) 2023
[9648.0, 11369.0, 12506.0]
employed (no.) 2023
[24969.0, 29153.0, 33682.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[3082.0, 3269.0, 3820.0]
employed (no.) 2023
[29457.0, 32942.0, 37265.0]
employed (no.) 2023
[18317.0, 20163.0, 21172.0]
employed (no.) 2023
[10490.0, 10737.0, 11752.0]
employed (no.) 2023
[17922.0, 21766.0, 25109.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[12082.0, 13299.0, 17486.0]
employed (no.) 2023
[10635.0, 13263.0, 15204.0]
employed (no.) 2023
[7787.0, 7863.0, 8934.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[9130.0, 8832.0, 10363.0]
employed (no.) 2023
[7175.0, 7597.0, 9434.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[4843.0, 4469.0, 4720.0]
employed (no.) 2023
[12225.0, 13046.0, 14736.0]
employed (no.) 2023
[7603.0, 8208.0, 10532.0]
employed (no.) 2023
[12505.0, 15721.0, 21564.0]
employed (no.) 2023
[1453.0, 1400.0, 1477.0]
employed (no.) 2023
[19789.0, 20861.0, 23369.0]
employed (no.) 2023
[4504.0, 4429.0, 4760.0]
employed (no.) 2023
[38810.0, 40555.0, 46996.0]
employed (no.) 2023
[4504.0, 4429.0, 4760.0]
employed (no.) 2023
[21319.0, 22153.0, 25761.0]
employed (no.) 2023
[3526.0, 3457.0, 3919.0]
employed (no.) 2023
[34892.0, 42653.0, 57187.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[17959.0, 19620.0, 20920.0]
employed (no.) 2023
[21166.0, 21972.0, 24745.0]
employed (no.) 2023
[21166.0, 21972.0, 24745.0]
employed (no.) 2023
[9277.0, 10012.0, 10956.0]
employed (no.) 2023
[6290.0, 6423.0, 7163.0]
employed (no.) 2023
[7455.0, 8876.0, 12382.0]
employed (no.) 2023
[55833.0, 67942.0, 88622.0]
employed (no.) 2023
[2725.0, 2483.0, 2656.0]
employed (no.) 2023
[19040.0, 20714.0, 21857.0]
employed (no.) 2023
[3082.0, 3269.0, 3820.0]
employed (no.) 2023
[19708.0, 20406.0, 23419.0]
employed (no.) 2023
[6290.0, 6423.0, 7163.0]
employed (no.) 2023
[36404.0, 50771.0, 68651.0]
employed (no.) 2023
[2380.0, 2365.0, 2558.0]
employed (no.) 2023
[7047.0, 7387.0, 8573.0]
employed (no.) 2023
[7047.0, 7387.0, 8573.0]
employed (no.) 2023
[13617.0, 13752.0, 15444.0]

,employed (no.) 2011,employed (no.) 2016,employed (no.) 2021,employed (no.) 2023
0,20267.0,19917.0,20755.0,20654.600000
1,25316.0,28076.0,38130.0,39477.133333
2,3626.0,4667.0,5832.0,6252.533333
3,25316.0,28076.0,38130.0,39477.133333
4,25316.0,28076.0,38130.0,39477.133333
...,...,...,...,...
11340,17761.0,18895.0,20251.0,20712.000000
11341,2174.0,2377.0,3485.0,3596.366667
11342,12197.0,16831.0,23396.0,25313.966667
11343,16540.0,16313.0,17455.0,17409.833333
11344,16540.0,16313.0,17455.0,17409.833333

In [83]:
# median weekly household rental payment ($) 2023
weekly_rent_2023_column = data.apply(lambda x:
    predict_2023_value([x["median weekly household rental payment ($) 2011"], 
     x["median weekly household rental payment ($) 2016"],
     x["median weekly household rental payment ($) 2021"]], 
    "median weekly household rental payment ($) 2023"), axis=1)

data = pd.concat([data, weekly_rent_2023_column], axis=1)

"""
data = data.drop(["employed (no.) 2011", 
     "employed (no.) 2016",
     "employed (no.) 2021"], axis=1)
"""

data[["median weekly household rental payment ($) 2011", 
     "median weekly household rental payment ($) 2016",
     "median weekly household rental payment ($) 2021", 
     "median weekly household rental payment ($) 2023"]]

[367.0, 420.3333333333333, 466.0]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[271.0, 330.0, 405.0]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[255.5, 300.5, 334.5]
median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[360.0, 391.0, 406.5]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[240.0, 280.0, 330.0]
median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
median weekly household rental payment ($) 2023
[257.5, 296.5, 334.0]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[276.75, 316.0, 359.75]
median weekly household rental payment ($) 2023
[200.0, 250.0, 285.0]
median weekly household rental payment ($) 2023
[323.0, 381.0, 430.0]
median weekly household rental payment ($) 2023
[160.0, 180.0, 210.0]
median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
median weekly household rental payment ($) 2023
[276.75, 316.0, 359.75]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
median weekly household rental payment ($) 2023
[287.0, 334.0, 380.0]
median weekly household rental payment ($) 2023
[267.0, 324.5, 378.75]
median weekly household rental payment ($) 2023
[306.5, 345.5, 384.5]
median weekly household rental payment ($) 2023
[150.0, 180.0, 214.0]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[267.0, 324.5, 378.75]
median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[305.5, 356.0, 393.5]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[323.0, 381.0, 430.0]
median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[192.5, 250.0, 310.0]
median weekly household rental payment ($) 2023
[305.0, 331.0, 367.0]
median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[175.0, 208.0, 250.0]
median weekly household rental payment ($) 2023
[375.3333333333333, 414.6666666666667, 426.0]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[200.0, 250.0, 285.0]
median weekly household rental payment ($) 2023
[277.5, 328.0, 384.5]
median weekly household rental payment ($) 2023
[340.0, 405.0, 500.0]
median weekly household rental payment ($) 2023
[160.0, 195.0, 220.0]
median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
median weekly household rental payment ($) 2023
[160.0, 180.0, 210.0]
median weekly household rental payment ($) 2023
[170.0, 200.0, 235.0]
median weekly household rental payment ($) 2023
[255.5, 300.5, 334.5]
median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
median weekly household rental payment ($) 2023
[255.5, 300.5, 334.5]
median weekly household rental payment ($) 2023
[143.0, 170.0, 200.0]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[110.0, 140.0, 158.0]
median weekly household rental payment ($) 2023
[110.0, 140.0, 158.0]
median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[240.0, 280.0, 330.0]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
median weekly household rental payment ($) 2023
[250.0, 295.0, 350.0]
median weekly household rental payment ($) 2023
[200.0, 250.0, 300.0]
median weekly household rental payment ($) 2023
[228.0, 252.5, 293.5]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[223.5, 263.75, 298.75]
median weekly household rental payment ($) 2023
[297.0, 338.0, 387.5]
median weekly household rental payment ($) 2023
[195.0, 230.0, 270.0]
median weekly household rental payment ($) 2023
[176.0, 200.0, 250.0]
median weekly household rental payment ($) 2023
[277.5, 328.0, 384.5]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[269.25, 326.25, 381.25]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
median weekly household rental payment ($) 2023
[170.0, 200.0, 235.0]
median weekly household rental payment ($) 2023
[241.66666666666663, 286.6666666666667, 338.3333333333333]
median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
median weekly household rental payment ($) 2023
[233.0, 260.0, 330.0]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[315.25, 355.0, 388.0]
median weekly household rental payment ($) 2023
[165.0, 200.0, 250.0]
median weekly household rental payment ($) 2023
[335.0, 385.5, 415.5]
median weekly household rental payment ($) 2023
[200.0, 250.0, 280.0]
median weekly household rental payment ($) 2023
[360.0, 391.0, 406.5]
median weekly household rental payment ($) 2023
[176.0, 200.0, 250.0]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
median weekly household rental payment ($) 2023
[301.1, 476.7, 378.0]
median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
median weekly household rental payment ($) 2023
[100.0, 110.0, 150.0]
median weekly household rental payment ($) 2023
[250.75, 294.5, 336.75]
median weekly household rental payment ($) 2023
[250.0, 295.0, 350.0]
median weekly household rental payment ($) 2023
[301.1, 476.7, 378.0]
median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
median weekly household rental payment ($) 2023
[360.0, 391.0, 406.5]
median weekly household rental payment ($) 2023
[286.0, 329.3333333333333, 374.3333333333333]
median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[130.0, 150.0, 180.0]
median weekly household rental payment ($) 2023
[180.0, 220.0, 260.0]
median weekly household rental payment ($) 2023
[260.0, 300.0, 380.0]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[350.0, 400.0, 426.0]
median weekly household rental payment ($) 2023
[310.57142857142856, 333.0, 375.2857142857143]
median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
median weekly household rental payment ($) 2023
[130.0, 150.0, 182.0]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
median weekly household rental payment ($) 2023
[230.0, 275.0, 320.0]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
median weekly household rental payment ($) 2023
[175.0, 208.0, 250.0]
median weekly household rental payment ($) 2023
[175.0, 208.0, 250.0]
median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
median weekly household rental payment ($) 2023
[205.0, 250.0, 290.0]
median weekly household rental payment ($) 2023
[277.5, 328.0, 384.5]
median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[170.0, 205.0, 245.0]
median weekly household rental payment ($) 2023
[170.0, 205.0, 245.0]
median weekly household rental payment ($) 2023
[150.0, 190.0, 250.0]
median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[375.3333333333333, 414.6666666666667, 426.0]
median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
median weekly household rental payment ($) 2023
[200.0, 250.0, 300.0]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[165.0, 200.0, 200.0]
median weekly household rental payment ($) 2023
[315.4, 370.8, 422.8]
median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
median weekly household rental payment ($) 2023
[160.0, 200.0, 240.0]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[205.0, 240.0, 286.5]
median weekly household rental payment ($) 2023
[332.3333333333333, 392.0, 420.6666666666667]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[340.0, 405.0, 500.0]
median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[205.0, 240.0, 286.5]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[205.0, 240.0, 286.5]
median weekly household rental payment ($) 2023
[288.0, 340.0, 390.0]
median weekly household rental payment ($) 2023
[143.0, 170.0, 200.0]
median weekly household rental payment ($) 2023
[228.0, 252.5, 293.5]
median weekly household rental payment ($) 2023
[195.0, 230.0, 270.0]
median weekly household rental payment ($) 2023
[170.0, 200.0, 240.0]
median weekly household rental payment ($) 2023
[165.0, 200.0, 250.0]
median weekly household rental payment ($) 2023
[154.5, 190.0, 220.0]
median weekly household rental payment ($) 2023
[185.0, 231.0, 280.0]
median weekly household rental payment ($) 2023
[288.3333333333333, 358.3333333333333, 410.0]
median weekly household rental payment ($) 2023
[353.3333333333333, 405.0, 434.0]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[332.3333333333333, 392.0, 420.6666666666667]
median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
median weekly household rental payment ($) 2023
[250.0, 293.3333333333333, 330.6666666666667]
median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
median weekly household rental payment ($) 2023
[185.0, 231.0, 280.0]
median weekly household rental payment ($) 2023
[468.0, 485.0, 471.3333333333333]
median weekly household rental payment ($) 2023
[195.0, 230.0, 270.0]
median weekly household rental payment ($) 2023
[200.0, 250.0, 285.0]
median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
median weekly household rental payment ($) 2023
[180.0, 220.0, 260.0]
median weekly household rental payment ($) 2023
[260.0, 312.0, 356.0]
median weekly household rental payment ($) 2023
[267.0, 324.5, 378.75]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[180.0, 220.0, 260.0]
median weekly household rental payment ($) 2023
[285.0, 337.0, 376.0]
median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
median weekly household rental payment ($) 2023
[170.0, 200.0, 250.0]
median weekly household rental payment ($) 2023
[110.0, 140.0, 158.0]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
median weekly household rental payment ($) 2023
[160.0, 200.0, 240.0]
median weekly household rental payment ($) 2023
[195.0, 246.0, 280.0]
median weekly household rental payment ($) 2023
[205.0, 253.0, 310.0]
median weekly household rental payment ($) 2023
[287.0, 334.0, 380.0]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[283.0, 400.0, 425.0]
median weekly household rental payment ($) 2023
[332.6666666666667, 377.0, 397.0]
median weekly household rental payment ($) 2023
[380.0, 439.0, 453.0]
median weekly household rental payment ($) 2023
[171.66666666666666, 210.0, 253.3333333333333]
median weekly household rental payment ($) 2023
[195.0, 246.0, 280.0]
median weekly household rental payment ($) 2023
[335.0, 385.5, 415.5]
median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
median weekly household rental payment ($) 2023
[140.0, 180.0, 200.0]
median weekly household rental payment ($) 2023
[190.0, 235.0, 280.0]
median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
median weekly household rental payment ($) 2023
[311.0, 356.0, 387.3333333333333]
median weekly household rental payment ($) 2023
[286.0, 329.3333333333333, 374.3333333333333]
median weekly household rental payment ($) 2023
[286.0, 329.3333333333333, 374.3333333333333]
median weekly household rental payment ($) 2023
[255.5, 300.5, 334.5]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[335.3333333333333, 389.6666666666667, 418.3333333333333]
median weekly household rental payment ($) 2023
[223.5, 263.75, 298.75]
median weekly household rental payment ($) 2023
[223.5, 263.75, 298.75]
median weekly household rental payment ($) 2023
[354.0, 397.0, 423.5]
median weekly household rental payment ($) 2023
[325.0, 378.0, 414.5]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[165.0, 200.0, 250.0]
median weekly household rental payment ($) 2023
[233.0, 260.0, 330.0]
median weekly household rental payment ($) 2023
[309.6, 334.4, 372.8]
median weekly household rental payment ($) 2023
[267.0, 324.5, 378.75]
median weekly household rental payment ($) 2023
[347.3333333333333, 383.3333333333333, 404.0]
median weekly household rental payment ($) 2023
[180.0, 250.0, 280.0]
median weekly household rental payment ($) 2023
[375.3333333333333, 414.6666666666667, 426.0]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[207.5, 240.0, 275.0]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[195.0, 230.0, 270.0]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[276.75, 316.0, 359.75]
median weekly household rental payment ($) 2023
[240.0, 270.0, 340.0]
median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
median weekly household rental payment ($) 2023
[307.3333333333333, 327.6666666666667, 363.6666666666667]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[150.0, 180.0, 215.0]
median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
median weekly household rental payment ($) 2023
[380.0, 439.0, 453.0]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[125.0, 145.0, 170.0]
median weekly household rental payment ($) 2023
[397.5, 457.5, 507.5]
median weekly household rental payment ($) 2023
[154.5, 190.0, 220.0]
median weekly household rental payment ($) 2023
[218.75, 259.5, 302.0]
median weekly household rental payment ($) 2023
[307.1666666666667, 356.6666666666667, 404.8333333333333]
median weekly household rental payment ($) 2023
[226.66666666666663, 275.0, 311.6666666666667]
median weekly household rental payment ($) 2023
[316.25, 359.5, 397.0]
median weekly household rental payment ($) 2023
[260.0, 312.0, 356.0]
median weekly household rental payment ($) 2023
[170.0, 200.0, 235.0]
median weekly household rental payment ($) 2023
[205.0, 240.0, 286.5]
median weekly household rental payment ($) 2023
[266.6666666666667, 313.0, 365.3333333333333]
median weekly household rental payment ($) 2023
[180.0, 220.0, 260.0]
median weekly household rental payment ($) 2023
[335.0, 395.0, 440.5]
median weekly household rental payment ($) 2023
[320.0, 372.5, 415.0]
median weekly household rental payment ($) 2023

,median weekly household rental payment ($) 2011,median weekly household rental payment ($) 2016,median weekly household rental payment ($) 2021,median weekly household rental payment ($) 2023
0,367.00,420.333333,466.00,487.077778
1,269.25,326.250000,381.25,403.983333
2,271.00,330.000000,405.00,429.133333
3,269.25,326.250000,381.25,403.983333
4,269.25,326.250000,381.25,403.983333
...,...,...,...,...
11340,402.00,473.000000,535.50,563.616667
11341,240.00,270.000000,340.00,353.333333
11342,483.50,501.000000,461.00,466.083333
11343,397.50,457.500000,507.50,531.166667
11344,397.50,457.500000,507.50,531.166667

In [84]:
# average family size (no. of persons) 2023
weekly_rent_2023_column = data.apply(lambda x:
    predict_2023_value([x["average family size (no. of persons) 2011"], 
     x["average family size (no. of persons) 2016"],
     x["average family size (no. of persons) 2021"]], 
    "average family size (no. of persons) 2023"), axis=1)

data = pd.concat([data, weekly_rent_2023_column], axis=1)

"""
data = data.drop(["employed (no.) 2011", 
     "employed (no.) 2016",
     "employed (no.) 2021"], axis=1)
"""

data[["average family size (no. of persons) 2011", 
     "average family size (no. of persons) 2016",
     "average family size (no. of persons) 2021", 
     "average family size (no. of persons) 2023"]]

[3.1333333333333333, 3.1333333333333333, 3.033333333333333]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.7, 2.7, 2.7]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[3.025, 3.025, 3.025]
average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.45, 2.45, 2.5]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
average family size (no. of persons) 2023
[3.125, 3.075, 3.05]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.7, 2.7, 2.6]
average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
average family size (no. of persons) 2023
[2.966666666666667, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.925, 2.975, 2.95]
average family size (no. of persons) 2023
[3.05, 3.05, 3.05]
average family size (no. of persons) 2023
[2.8, 2.8, 2.7]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.925, 2.975, 2.95]
average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.95, 2.9, 2.85]
average family size (no. of persons) 2023
[3.25, 3.1500000000000004, 3.05]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.433333333333333, 2.4, 2.4]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.7, 2.7, 2.6]
average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
average family size (no. of persons) 2023
[3.1, 3.1, 3.1]
average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[3.025, 3.025, 3.025]
average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
average family size (no. of persons) 2023
[3.025, 3.025, 3.025]
average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
average family size (no. of persons) 2023
[2.95, 2.95, 2.85]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.925, 2.875, 2.9]
average family size (no. of persons) 2023
[3.05, 3.1500000000000004, 3.25]
average family size (no. of persons) 2023
[3.05, 3.0, 3.0]
average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.8666666666666667, 2.8666666666666667, 2.833333333333333]
average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.35, 3.35, 3.3]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[3.0, 3.0, 2.9]
average family size (no. of persons) 2023
[3.0, 3.0, 2.9]
average family size (no. of persons) 2023
[2.45, 2.45, 2.5]
average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
average family size (no. of persons) 2023
[3.2299999999999995, 3.24, 3.35]
average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[3.05, 3.05, 3.05]
average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
average family size (no. of persons) 2023
[3.2299999999999995, 3.24, 3.35]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.45, 2.45, 2.5]
average family size (no. of persons) 2023
[3.0500000000000003, 3.0500000000000003, 2.983333333333333]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[2.9, 2.8, 2.7]
average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[3.157142857142857, 3.2142857142857144, 3.2142857142857144]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
average family size (no. of persons) 2023
[2.8, 2.7, 2.8]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.85, 2.8, 2.75]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.7, 2.7, 2.7]
average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.433333333333333, 2.4, 2.4]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.8, 2.8, 2.7]
average family size (no. of persons) 2023
[3.14, 3.12, 3.06]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
average family size (no. of persons) 2023
[2.8000000000000003, 2.8000000000000003, 2.733333333333333]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[3.1, 3.1, 3.1]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
average family size (no. of persons) 2023
[2.8, 2.9, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
average family size (no. of persons) 2023
[2.95, 2.95, 2.85]
average family size (no. of persons) 2023
[3.05, 3.0, 3.0]
average family size (no. of persons) 2023
[3.0, 3.0, 2.9]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
average family size (no. of persons) 2023
[2.766666666666667, 2.733333333333333, 2.7]
average family size (no. of persons) 2023
[2.966666666666667, 3.0, 3.0]
average family size (no. of persons) 2023
[2.7, 2.6333333333333333, 2.566666666666667]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.8000000000000003, 2.8000000000000003, 2.733333333333333]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.1333333333333333, 3.1666666666666665, 3.2]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[2.766666666666667, 2.733333333333333, 2.7]
average family size (no. of persons) 2023
[2.3666666666666667, 2.4, 2.466666666666667]
average family size (no. of persons) 2023
[3.05, 3.0, 3.0]
average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
average family size (no. of persons) 2023
[3.1, 3.2, 3.1]
average family size (no. of persons) 2023
[2.925, 2.975, 2.95]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.8, 2.8, 2.7]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[3.0, 3.0, 3.0]
average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
average family size (no. of persons) 2023
[2.6, 2.6, 2.5]
average family size (no. of persons) 2023
[2.966666666666667, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[2.6, 2.5, 2.4]
average family size (no. of persons) 2023
[2.7, 2.733333333333333, 2.6666666666666665]
average family size (no. of persons) 2023
[2.55, 2.6, 2.5]
average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
average family size (no. of persons) 2023
[3.0, 2.9, 2.9]
average family size (no. of persons) 2023
[3.0, 3.0, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[3.0500000000000003, 3.0500000000000003, 2.983333333333333]
average family size (no. of persons) 2023
[3.0500000000000003, 3.0500000000000003, 2.983333333333333]
average family size (no. of persons) 2023
[3.025, 3.025, 3.025]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.9, 2.966666666666667, 2.9]
average family size (no. of persons) 2023
[2.925, 2.875, 2.9]
average family size (no. of persons) 2023
[2.925, 2.875, 2.9]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.8, 2.7, 2.7]
average family size (no. of persons) 2023
[3.04, 3.04, 2.96]
average family size (no. of persons) 2023
[2.925, 2.975, 2.95]
average family size (no. of persons) 2023
[2.8666666666666667, 2.8666666666666667, 2.833333333333333]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.433333333333333, 2.4, 2.4]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[3.05, 3.0, 3.0]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[2.6, 2.6, 2.5]
average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
average family size (no. of persons) 2023
[3.2, 3.233333333333333, 3.2]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
average family size (no. of persons) 2023
[2.55, 2.6, 2.5]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[3.1500000000000004, 3.2, 3.1]
average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
average family size (no. of persons) 2023
[2.9625, 2.95, 2.9125]
average family size (no. of persons) 2023
[3.033333333333333, 3.0500000000000003, 3.016666666666667]
average family size (no. of persons) 2023
[3.033333333333333, 3.0, 2.9333333333333336]
average family size (no. of persons) 2023
[3.075, 3.05, 3.0]
average family size (no. of persons) 2023
[3.1, 3.2, 3.1]
average family size (no. of persons) 2023
[2.9, 2.8, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
average family size (no. of persons) 2023
[2.9, 2.9333333333333336, 2.8666666666666667]
average family size (no. of persons) 2023
[2.9, 2.9, 2.8]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[3.05, 3.1, 3.05]
average family size (no. of persons) 2023
[2.95, 2.9, 2.9]
average family size (no. of persons) 2023
[2.9, 3.0, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9, 2.85]
average family size (no. of persons) 2023
[2.966666666666667, 2.9, 2.8666666666666667]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.7, 2.7, 2.6]
average family size (no. of persons) 2023
[2.8, 2.75, 2.75]
average family size (no. of persons) 2023
[2.833333333333333, 2.833333333333333, 2.766666666666667]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
average family size (no. of persons) 2023
[2.95, 2.9, 2.85]
average family size (no. of persons) 2023
[2.9, 2.9, 2.9]
average family size (no. of persons) 2023
[2.7, 2.733333333333333, 2.6666666666666665]
average family size (no. of persons) 2023
[2.85, 2.9, 2.8]
average family size (no. of persons) 2023
[2.6, 2.5, 2.4]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.1, 3.0, 3.0]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[2.6, 2.7, 2.6]
average family size (no. of persons) 2023
[2.95, 2.95, 2.9]
average family size (no. of persons) 2023
[3.2, 3.2, 3.2]
average family size (no. of persons) 2023
[2.9, 2.8, 2.75]
average family size (no. of persons) 2023
[2.466666666666667, 2.5, 2.5]
average family size (no. of persons) 2023
[2.95, 2.95, 2.85]
average family size (no. of persons) 2023
[2.8, 2.8, 2.75]
average family size (no. of persons) 2023
[2.8, 2.8, 2.8]
average family size (no. of persons) 2023
[2.925, 2.975, 3.0]
average family size (no. of persons) 2023
[2.725, 2.675, 2.625]
average family size (no. of persons) 2023
[3.1, 3.1, 3.0]
average family size (no. of persons) 2023
[2.9, 3.0, 2.9]
average family size (no. of persons) 2023
[2.95, 2.9, 2.85]
average family size (no. of persons) 2023
[2.7, 2.7, 2.7]
average family size (no. of persons) 2023
[3.111111111111111, 3.1888888888888887, 3.2444444444444445]
average family size (no. of persons) 2023
[2.481818181818182, 2.5, 2.5]
average family size (no. of persons) 2023

,average family size (no. of persons) 2011,average family size (no. of persons) 2016,average family size (no. of persons) 2021,average family size (no. of persons) 2023
0,3.133333,3.133333,3.033333,3.030000
1,2.925000,2.975000,3.000000,3.019167
2,2.700000,2.700000,2.700000,2.700000
3,2.925000,2.975000,3.000000,3.019167
4,2.925000,2.975000,3.000000,3.019167
...,...,...,...,...
11340,3.050000,3.100000,3.000000,3.015000
11341,2.600000,2.600000,2.500000,2.496667
11342,2.350000,2.375000,2.450000,2.461667
11343,3.150000,3.200000,3.100000,3.115000
11344,3.150000,3.200000,3.100000,3.115000

In [85]:
# remove 2011 and 2016 features for postcode information
"""
for col_name in data.columns:
    col_name_list = col_name.split(" ")
    if col_name_list[-1] == "2011" or col_name_list[-1] == "2016":
        data = data.drop(col_name, axis=1)
        print(col_name)
"""

'\nfor col_name in data.columns:\n    col_name_list = col_name.split(" ")\n    if col_name_list[-1] == "2011" or col_name_list[-1] == "2016":\n        data = data.drop(col_name, axis=1)\n        print(col_name)\n'

In [86]:
# drop irrelevant features for predictions
data = data.drop(["name", "coordinates", "property features", "nbn", "geometry"], axis=1)