Find the SA2 district for each rental property

In [1]:
import geopandas as gpd
import pandas as pd

In [5]:
sa2_districts_sf = gpd.read_file("../data/landing/sa2/SA2_2021_AUST_GDA2020.shp")
rent_data = pd.read_csv("../data/curated/rental_data.csv")

In [7]:
from shapely.geometry import Point
import ast

# Convert the string to a list of floats
rent_data['coordinates'] = rent_data['coordinates'].apply(ast.literal_eval)

# Convert the list of floats to Point geometry (note the order: (longitude, latitude))
rent_data['geometry'] = rent_data['coordinates'].apply(lambda x: Point(x[1], x[0]))

In [8]:
# Convert DataFrame to GeoDataFrame
rent_data_sf = gpd.GeoDataFrame(rent_data, geometry='geometry', crs="EPSG:4326")

rent_data_sf.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000.0,POINT (144.96963 -37.80852)
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000.0,POINT (144.96940 -37.80820)
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000.0,POINT (144.96027 -37.80726)
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000.0,POINT (144.95926 -37.81127)
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000.0,POINT (144.95865 -37.80543)

In [9]:
rent_data_sf = gpd.sjoin(rent_data_sf, sa2_districts_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

rent_data_sf.head()

/root/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):
/tmp/ipykernel_116099/3498390347.py:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: EPSG:7844

  rent_data_sf = gpd.sjoin(rent_data_sf, sa2_districts_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,index_right,SA2_CODE21,SA2_NAME21
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000.0,POINT (144.96963 -37.80852),779.0,206041503,Melbourne CBD - East
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000.0,POINT (144.96940 -37.80820),779.0,206041503,Melbourne CBD - East
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000.0,POINT (144.96027 -37.80726),780.0,206041504,Melbourne CBD - North
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000.0,POINT (144.95926 -37.81127),780.0,206041504,Melbourne CBD - North
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000.0,POINT (144.95865 -37.80543),782.0,206041506,North Melbourne

In [10]:
rent_data_sf = rent_data_sf.drop(columns='index_right')

In [11]:
rent_data_sf.to_csv("../data/curated/rental_data_sf.csv", index=False)

In [2]:
rent_data_sf = pd.read_csv("../data/curated/rental_data_sf.csv")

In [3]:
from shapely import wkt

In [4]:
rent_data_sf['geometry'] = rent_data_sf['geometry'].apply(wkt.loads)

In [6]:
rent_data_sf = rent_data_sf[rent_data_sf['SA2_CODE21'].notnull()]

rent_data_sf = rent_data_sf[rent_data_sf['Postcode'].notnull()]

rent_data_sf.SA2_CODE21 = rent_data_sf.SA2_CODE21.astype(int)

rent_data_sf.Postcode = rent_data_sf.Postcode.astype(int)

In [7]:
rent_data_sf.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,SA2_CODE21,SA2_NAME21
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000,POINT (144.9696285 -37.8085173),206041503,Melbourne CBD - East
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000,POINT (144.9693999 -37.8082025),206041503,Melbourne CBD - East
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000,POINT (144.9602708 -37.8072623),206041504,Melbourne CBD - North
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000,POINT (144.9592612 -37.8112667),206041504,Melbourne CBD - North
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000,POINT (144.9586458 -37.8054298),206041506,North Melbourne

In [8]:
rent_data_sf[["Postcode", "SA2_CODE21"]]

       Postcode  SA2_CODE21
0          3000   206041503
1          3000   206041503
2          3000   206041504
3          3000   206041504
4          3000   206041506
...         ...         ...
11803      3015   213021344
11804      3020   213011336
11805      3840   205041096
11806      3046   210031535
11807      3136   211031451

[11798 rows x 2 columns]

In [12]:
postcode_sa2_conversion = rent_data_sf[['Postcode', 'SA2_CODE21']].drop_duplicates(subset=['Postcode', 'SA2_CODE21'])

In [13]:
postcode_sa2_conversion

       Postcode  SA2_CODE21
0          3000   206041503
2          3000   206041504
4          3000   206041506
7          3000   206041118
8          3000   206041117
...         ...         ...
11651      3393   215011394
11654      3400   215011388
11674      3414   215011390
11675      3418   215011390
11677      3427   210041539

[765 rows x 2 columns]

In [14]:
postcode_sa2_conversion.groupby("Postcode").size()

Postcode
3000    12
3002     1
3003     2
3004     8
3006     4
        ..
3988     1
3991     1
3992     1
3995     1
3996     1
Length: 428, dtype: int64

In [24]:
sa2_info = pd.read_csv("../data/curated/suburb_info.csv")

sa2_info.head()

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),Unemployment rate (%),Participation rate (%),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
0,206041506,15998.0,6597.7,8813.0,667.0,7.0,68.3,1281.0,242.5,381.0,2.6,3267.0,9277.0
1,206041124,7446.0,1838.9,3980.0,441.0,10.0,64.9,1385.0,404.9,396.0,2.6,1032.0,2819.0
2,206041117,17198.0,9456.2,8749.0,1141.0,11.5,62.7,971.0,181.9,365.0,2.4,2593.0,10594.0
3,206041503,10205.0,12724.4,5855.0,521.0,8.2,67.7,1167.0,80.2,375.0,2.3,1732.0,7375.0
4,206041505,16179.0,16096.9,10129.0,927.0,8.4,73.2,1116.0,100.5,376.0,2.2,2951.0,12007.0

In [25]:
# Merge the dataframes on the relevant columns
merged_df = pd.merge(postcode_sa2_conversion, sa2_info, left_on='SA2_CODE21', right_on='SA2_codes', how='inner')

# Perform groupby operation and aggregate the columns as specified
agg_funcs = {
    'Estimated resident population (no.)': 'sum',
    'Employed (no.)': 'sum',
    'Unemployed (no.)': 'sum',
    'Land area (ha)': 'sum',
    'Total families (no.)': 'sum',
    'Total dwellings (no.)': 'sum',
    'Median equivalised total household income (weekly) ($)': 'mean',
    'Median weekly household rental payment ($)': 'mean'
}

result_df = merged_df.groupby('Postcode').agg(agg_funcs).reset_index()

print(result_df)

     Postcode  Estimated resident population (no.)  Employed (no.)  \
0        3000                             158246.0         88622.0
1        3002                               4962.0          3078.0
2        3003                              23617.0         13642.0
3        3004                             108890.0         64480.0
4        3006                              36975.0         23396.0
..        ...                                  ...             ...
423      3988                               9783.0          4596.0
424      3991                              26723.0         10846.0
425      3992                              26723.0         10846.0
426      3995                              26723.0         10846.0
427      3996                              26723.0         10846.0

     Unemployed (no.)  Land area (ha)  Total families (no.)  \
0              6958.0          2408.8               33336.0
1               100.0           290.0                1199.0
2               994.0           325.0                4978.0
3              4738.0          1360.5               22651.0
4              1365.0          1118.7                8593.0
..                ...             ...                   ...
423             166.0         60069.1                2721.0
424             451.0         72876.3                7364.0
425             451.0         72876.3                7364.0
426             451.0         72876.3                7364.0
427             451.0         72876.3                7364.0

     Total dwellings (no.)  \
0                  99364.0
1                   3453.0
2                  14049.0
3                  74682.0
4                  25941.0
..                     ...
423                 4366.0
424                16030.0
425                16030.0
426                16030.0
427                16030.0

     Median equivalised total household income (weekly) ($)  \
0                                          1343.818182
1                                          1921.000000
2                                          1309.000000
3                                          1403.250000
4                                          1602.750000
..                                                 ...
423                                         871.000000
424                                         767.000000
425                                         767.000000
426                                         767.000000
427                                         767.000000

     Median weekly household rental payment ($)
0                                    412.727273
1                                    480.000000
2                                    385.500000
3                                    410.375000
4                                    461.000000
..                                          ...
423                                  280.000000
424                                  298.000000
425                                  298.000000
426                                  298.000000
427                                  298.000000

[428 rows x 9 columns]

In [27]:
merged_df.to_csv("../data/curated/postcode_info_2021.csv", index=False)