Find the SA2 district for each rental property

In [4]:
import geopandas as gpd
import pandas as pd

In [5]:
sa2_districts_sf = gpd.read_file("../data/landing/sa2/SA2_2021_AUST_GDA2020.shp")
rent_data = pd.read_csv("../data/curated/rental_data.csv")

In [7]:
from shapely.geometry import Point
import ast

# Convert the string to a list of floats
rent_data['coordinates'] = rent_data['coordinates'].apply(ast.literal_eval)

# Convert the list of floats to Point geometry (note the order: (longitude, latitude))
rent_data['geometry'] = rent_data['coordinates'].apply(lambda x: Point(x[1], x[0]))

In [8]:
# Convert DataFrame to GeoDataFrame
rent_data_sf = gpd.GeoDataFrame(rent_data, geometry='geometry', crs="EPSG:4326")

rent_data_sf.head()

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000.0,POINT (144.96963 -37.80852)
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000.0,POINT (144.96940 -37.80820)
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000.0,POINT (144.96027 -37.80726)
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000.0,POINT (144.95926 -37.81127)
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000.0,POINT (144.95865 -37.80543)

In [9]:
rent_data_sf = gpd.sjoin(rent_data_sf, sa2_districts_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

rent_data_sf.head()

/root/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3445: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):
/tmp/ipykernel_116099/3498390347.py:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: EPSG:7844

  rent_data_sf = gpd.sjoin(rent_data_sf, sa2_districts_sf[['SA2_CODE21', 'SA2_NAME21', 'geometry']], how="left", op="within")

,name,cost_text,coordinates,property type,beds,baths,parking,title,description,property features,NBN,Weekly Rent Amount,Postcode,geometry,index_right,SA2_CODE21,SA2_NAME21
0,5401/308 Exhibition Street Melbourne VIC 3000,"$3,750 weekly","[-37.8085173, 144.9696285]",Apartment / Unit / Flat,3 Beds,2 Baths,4 Parking,"BRAND NEW AT THE SAPHIRE - 3 BDR. 2.5 BTH, 4 ...",['Designed by Cox Architects and Fender Katsal...,['Built in wardrobes*'],No NBN,3750.0,3000.0,POINT (144.96963 -37.80852),779.0,206041503,Melbourne CBD - East
1,4904/63 Latrobe St Melbourne VIC 3000,"$2,900/week","[-37.8082025, 144.9693999]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Brand New luxurious 3 bedroom residence | Home...,['Welcome to your exclusive opportunity to res...,"['INSIDE:', 'Gym', 'Intercom', 'Floorboards', ...",No NBN,2900.0,3000.0,POINT (144.96940 -37.80820),779.0,206041503,Melbourne CBD - East
2,6703/500 Elizabeth Street Melbourne VIC 3000,"$2,800","[-37.8072623, 144.9602708]",Apartment / Unit / Flat,3 Beds,3 Baths,1 Parking,3 bedroom 2.5 bathroom Penthhouse in Vision,"[""To apply, submit an enquiry and you'll recei...","['Intercom', 'Gym', 'Air conditioning', 'Study...",nbn® Fibre to the Premises (FTTP) is available...,2800.0,3000.0,POINT (144.96027 -37.80726),780.0,206041504,Melbourne CBD - North
3,4802/316-318 Queen Street Melbourne VIC 3000,$2500 Per Week,"[-37.8112667, 144.9592612]",Apartment / Unit / Flat,3 Beds,3 Baths,2 Parking,Incredibly luxurious penthouse in CBD,"[""From the moment you step inside, you'll be c...",[],No NBN,2500.0,3000.0,POINT (144.95926 -37.81127),780.0,206041504,Melbourne CBD - North
4,1201/543 Elizabeth Street Melbourne VIC 3000,"$2,500 per week","[-37.8054298, 144.9586458]",Apartment / Unit / Flat,4 Beds,4 Baths,2 Parking,Brand-new luxury Penthouse in the heart of the...,"[""This stunning addition to the north of the C...",[],No NBN,2500.0,3000.0,POINT (144.95865 -37.80543),782.0,206041506,North Melbourne

In [10]:
rent_data_sf = rent_data_sf.drop(columns='index_right')

In [11]:
rent_data_sf.to_csv("../data/curated/rental_data_sf.csv", index=False)