Use the average growth rate between 2011 and 2021 to project census data for 2026

In [1]:
import pandas as pd

In [2]:
suburb_data_2011 = pd.read_csv("../data/curated/suburb_info_2011.csv")
suburb_data_2016 = pd.read_csv("../data/curated/suburb_info_2016.csv")
suburb_data_2021 = pd.read_csv("../data/curated/suburb_info_2021.csv")

In [3]:
suburb_data_2011.head()

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
0,206041506,17005.0,NaN,5933.0,579.0,6518.0,10571.0,876.0,NaN,340.0,2.6,2321.0,8113.0
1,206041124,8182.0,NaN,2873.0,406.0,3279.0,5802.0,1057.0,NaN,370.0,2.6,838.0,2595.0
2,206041117,20669.0,NaN,5606.0,912.0,6517.0,13093.0,464.0,NaN,340.0,2.5,2097.0,9072.0
3,206041503,11893.0,NaN,3618.0,400.0,4019.0,7011.0,840.0,NaN,422.0,2.3,1274.0,6738.0
4,206041505,16896.0,NaN,3670.0,395.0,4067.0,6653.0,909.0,NaN,401.0,2.2,1281.0,9620.0

In [7]:
cols = ["Estimated resident population (no.)", "Population density (persons/km2)",
        "Employed (no.)", "Unemployed (no.)", "In the Labour force (no.)", "Total persons aged 15 years and over (no.)",
        'Median equivalised total household income (weekly) ($)',
        'Land area (ha)', 'Median weekly household rental payment ($)', 
        'Average family size (no. of persons)', 'Total families (no.)', 'Total dwellings (no.)']

sa2_codes = suburb_data_2011["SA2_codes"].values

In [8]:
pred_suburb_data_2026 = (pd.DataFrame(columns= cols, index=sa2_codes)).rename_axis('SA2_Code', axis=1)

In [9]:
pred_suburb_data_2026.head()

SA2_Code,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
206041506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206041124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206041117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206041503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206041505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
def compute_growth_rate(df, col_name):
    """
    Calculate the average growth rate of a specific column for a given DataFrame.

    This function calculates the average growth rate for a specific column 'col_name' in the provided DataFrame 'df' by
    comparing values between three consecutive rows. The growth rate is computed as the percentage change between the
    second and first row and the percentage change between the first and zeroth row, then averaging these two growth rates.

    Parameters:
    df (DataFrame): A pandas DataFrame containing the data for which the growth rate is to be calculated.

    Returns:
    float: The average growth rate of the specified column.
    """
    growth_rate_1 = (df.iloc[2][col_name] - df.iloc[1][col_name]) / df.iloc[1][col_name]
    growth_rate_2 = (df.iloc[1][col_name] - df.iloc[0][col_name]) / df.iloc[0][col_name]
    return (growth_rate_1 + growth_rate_2)/2

In [11]:
suburb_data_2011['Year'] = 2011
suburb_data_2016['Year'] = 2016
suburb_data_2021['Year'] = 2021

combined_df = pd.concat([suburb_data_2011, suburb_data_2016, suburb_data_2021])

In [44]:
growth_rate = (pd.DataFrame(columns= cols, index=sa2_codes)).rename_axis('SA2_Code', axis=1)

In [17]:
growth_rate.head()

SA2_Code,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
206041506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206041124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206041117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206041503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206041505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
growth_rate.loc[206041506]["Estimated resident population (no.)"] = 2

growth_rate.loc[206041506]

SA2_Code
Estimated resident population (no.)                         2
Population density (persons/km2)                          NaN
Employed (no.)                                            NaN
Unemployed (no.)                                          NaN
In the Labour force (no.)                                 NaN
Total persons aged 15 years and over (no.)                NaN
Median equivalised total household income (weekly) ($)    NaN
Land area (ha)                                            NaN
Median weekly household rental payment ($)                NaN
Average family size (no. of persons)                      NaN
Total families (no.)                                      NaN
Total dwellings (no.)                                     NaN
Name: 206041506, dtype: object

In [27]:
combined_df

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.),Year
0,206041506,17005.0,NaN,5933.0,579.0,6518.0,10571.0,876.0,NaN,340.0,2.6,2321.0,8113.0,2011
1,206041124,8182.0,NaN,2873.0,406.0,3279.0,5802.0,1057.0,NaN,370.0,2.6,838.0,2595.0,2011
2,206041117,20669.0,NaN,5606.0,912.0,6517.0,13093.0,464.0,NaN,340.0,2.5,2097.0,9072.0,2011
3,206041503,11893.0,NaN,3618.0,400.0,4019.0,7011.0,840.0,NaN,422.0,2.3,1274.0,6738.0,2011
4,206041505,16896.0,NaN,3670.0,395.0,4067.0,6653.0,909.0,NaN,401.0,2.2,1281.0,9620.0,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,212031557,23753.0,2154.4,10730.0,620.0,11350.0,16959.0,980.0,1102.5,400.0,3.4,6132.0,7350.0,2021
518,212031300,21580.0,1656.6,9510.0,680.0,10185.0,16979.0,895.0,1302.7,342.0,3.1,5448.0,8053.0,2021
519,212031304,21834.0,1692.8,10469.0,579.0,11045.0,15816.0,1036.0,1289.8,380.0,3.3,5764.0,7025.0,2021
520,212031555,10642.0,1546.1,5187.0,251.0,5439.0,7432.0,1173.0,688.3,421.0,3.5,2841.0,3230.0,2021
521,212031556,15023.0,764.4,7620.0,341.0,7966.0,10423.0,1156.0,1965.4,410.0,3.4,4006.0,4585.0,2021

Compute the Growth rate for each column

In [45]:
for sa2_code in sa2_codes:
    for col in cols:
        df_postcode = combined_df[combined_df['SA2_codes'] == sa2_code].sort_values(by="Year")
        growth_rate.loc[sa2_code][col] = compute_growth_rate(df_postcode, col)

In [46]:
growth_rate

SA2_Code,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
206041506,-0.026564,NaN,0.21917,0.142844,0.205934,0.155331,0.239006,NaN,0.06117,0.0,0.186442,0.069348
206041124,-0.044277,NaN,0.177702,0.053137,0.16251,0.08897,0.147364,NaN,0.03591,0.0,0.11092,0.042591
206041117,-0.082097,NaN,0.252636,0.222226,0.231786,0.123912,0.58336,NaN,0.039737,-0.02,0.115729,0.081057
206041503,-0.065621,NaN,0.273257,0.232402,0.263203,0.193417,0.207177,NaN,-0.045507,0.0,0.177838,0.046421
206041505,-0.013496,NaN,0.66359,0.757953,0.657995,0.55463,0.139851,NaN,-0.021125,0.0,0.525467,0.119887
...,...,...,...,...,...,...,...,...,...,...,...,...
212031557,0.0711,NaN,0.833462,1.063597,0.845059,0.883854,0.094572,NaN,0.085139,0.030777,0.8448,0.075747
212031300,0.009006,NaN,0.059873,0.026722,0.055968,0.078997,0.168204,NaN,0.17,0.0,0.04625,0.028804
212031304,0.128637,NaN,0.634876,0.36558,0.614754,0.585044,0.225354,NaN,0.140951,0.000473,0.602081,0.145874
212031555,0.585348,NaN,NaN,NaN,NaN,NaN,-0.19889,NaN,0.52625,0.355303,NaN,0.542057
212031556,3.041821,NaN,21.007984,14.065476,20.786115,21.652083,0.283891,NaN,0.214768,0.044643,22.646644,1.84351

In [32]:
suburb_data_2011.head()

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.),Year
0,206041506,17005.0,NaN,5933.0,579.0,6518.0,10571.0,876.0,NaN,340.0,2.6,2321.0,8113.0,2011
1,206041124,8182.0,NaN,2873.0,406.0,3279.0,5802.0,1057.0,NaN,370.0,2.6,838.0,2595.0,2011
2,206041117,20669.0,NaN,5606.0,912.0,6517.0,13093.0,464.0,NaN,340.0,2.5,2097.0,9072.0,2011
3,206041503,11893.0,NaN,3618.0,400.0,4019.0,7011.0,840.0,NaN,422.0,2.3,1274.0,6738.0,2011
4,206041505,16896.0,NaN,3670.0,395.0,4067.0,6653.0,909.0,NaN,401.0,2.2,1281.0,9620.0,2011

In [33]:
suburb_data_2016.head()

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.),Year
0,206041506,17955.0,NaN,7050.0,889.0,7940.0,13796.0,849.0,NaN,386.0,2.6,2772.0,8722.0,2016
1,206041124,8294.0,NaN,3501.0,489.0,3996.0,6957.0,1130.0,NaN,403.0,2.6,974.0,2773.0,2016
2,206041117,21088.0,NaN,6507.0,1564.0,8065.0,17886.0,436.0,NaN,383.0,2.5,2531.0,9533.0,2016
3,206041503,12569.0,NaN,4801.0,679.0,5478.0,10379.0,795.0,NaN,466.0,2.3,1713.0,7195.0,2016
4,206041505,18780.0,NaN,6425.0,1035.0,7456.0,12880.0,793.0,NaN,450.0,2.2,2150.0,10027.0,2016

In [34]:
suburb_data_2021.head()

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.),Year
0,206041506,15998.0,6597.7,8813.0,667.0,9478.0,13873.0,1281.0,242.5,381.0,2.6,3267.0,9277.0,2021
1,206041124,7446.0,1838.9,3980.0,441.0,4421.0,6810.0,1385.0,404.9,396.0,2.6,1032.0,2819.0,2021
2,206041117,17198.0,9456.2,8749.0,1141.0,9888.0,15771.0,971.0,181.9,365.0,2.4,2593.0,10594.0,2021
3,206041503,10205.0,12724.4,5855.0,521.0,6373.0,9408.0,1167.0,80.2,375.0,2.3,1732.0,7375.0,2021
4,206041505,16179.0,16096.9,10129.0,927.0,11055.0,15112.0,1116.0,100.5,376.0,2.2,2951.0,12007.0,2021

Save the growth rate file

In [47]:
growth_rate.to_csv("../data/curated/growth_rates.csv", index_label="SA2_codes")

### Apply the growth rates to the 2021 census data

In [48]:
growth_rate = pd.read_csv("../data/curated/growth_rates.csv")

In [49]:
growth_rate.head()

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
0,206041506,-0.026564,NaN,0.219170,0.142844,0.205934,0.155331,0.239006,NaN,0.061170,0.00,0.186442,0.069348
1,206041124,-0.044277,NaN,0.177702,0.053137,0.162510,0.088970,0.147364,NaN,0.035910,0.00,0.110920,0.042591
2,206041117,-0.082097,NaN,0.252636,0.222226,0.231786,0.123912,0.583360,NaN,0.039737,-0.02,0.115729,0.081057
3,206041503,-0.065621,NaN,0.273257,0.232402,0.263203,0.193417,0.207177,NaN,-0.045507,0.00,0.177838,0.046421
4,206041505,-0.013496,NaN,0.663590,0.757953,0.657995,0.554630,0.139851,NaN,-0.021125,0.00,0.525467,0.119887

In [59]:
suburb_data_2021 = pd.read_csv("../data/curated/suburb_info_2021.csv")

suburb_data_2021 = suburb_data_2021.set_index("SA2_codes")

In [54]:
growth_rate.head()

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
0,206041506,-0.026564,NaN,0.219170,0.142844,0.205934,0.155331,0.239006,NaN,0.061170,0.00,0.186442,0.069348
1,206041124,-0.044277,NaN,0.177702,0.053137,0.162510,0.088970,0.147364,NaN,0.035910,0.00,0.110920,0.042591
2,206041117,-0.082097,NaN,0.252636,0.222226,0.231786,0.123912,0.583360,NaN,0.039737,-0.02,0.115729,0.081057
3,206041503,-0.065621,NaN,0.273257,0.232402,0.263203,0.193417,0.207177,NaN,-0.045507,0.00,0.177838,0.046421
4,206041505,-0.013496,NaN,0.663590,0.757953,0.657995,0.554630,0.139851,NaN,-0.021125,0.00,0.525467,0.119887

In [60]:
growth_rate = growth_rate.set_index("SA2_codes")

In [61]:
result = suburb_data_2021.multiply(growth_rate + 1)

In [62]:
result.head()

,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
SA2_codes,,,,,,,,,,,,
206041506,15573.022831,NaN,10744.544883,762.276644,11429.841751,16027.901855,1587.166689,NaN,404.305913,2.600,3876.106381,9920.345596
206041124,7116.313457,NaN,4687.255741,464.433414,5139.457999,7415.883960,1589.098519,NaN,410.220254,2.600,1146.469143,2939.064003
206041117,15786.102726,NaN,10959.315327,1394.559822,12179.895245,17725.220604,1537.442265,NaN,379.503859,2.352,2893.086041,11452.714121
206041503,9535.339581,NaN,7454.919226,642.081666,8050.394071,11227.665581,1408.775034,NaN,357.934956,2.300,2040.015104,7717.353597
206041505,15960.642386,NaN,16850.499329,1629.622124,18329.139429,23493.573557,1272.073290,NaN,368.057013,2.200,4501.653719,13446.486402

Now we just need to round the values

In [64]:
# List of columns to exclude from rounding
exclude_cols = ['Median equivalised total household income (weekly) ($)', 
                'Median weekly household rental payment ($)', 
                'Average family size (no. of persons)']

# Columns to be rounded
cols_to_round = [col for col in result.columns if col not in exclude_cols]

# Round the selected columns
result[cols_to_round] = result[cols_to_round].round()

In [65]:
result.head()

,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
SA2_codes,,,,,,,,,,,,
206041506,15573.0,NaN,10745.0,762.0,11430.0,16028.0,1587.166689,NaN,404.305913,2.600,3876.0,9920.0
206041124,7116.0,NaN,4687.0,464.0,5139.0,7416.0,1589.098519,NaN,410.220254,2.600,1146.0,2939.0
206041117,15786.0,NaN,10959.0,1395.0,12180.0,17725.0,1537.442265,NaN,379.503859,2.352,2893.0,11453.0
206041503,9535.0,NaN,7455.0,642.0,8050.0,11228.0,1408.775034,NaN,357.934956,2.300,2040.0,7717.0
206041505,15961.0,NaN,16850.0,1630.0,18329.0,23494.0,1272.073290,NaN,368.057013,2.200,4502.0,13446.0

Save the file

In [66]:
result.to_csv("../data/curated/suburb_info_2026.csv", index_label="SA2_codes")

In [67]:
result = pd.read_csv("../data/curated/suburb_info_2026.csv")

,SA2_codes,Estimated resident population (no.),Population density (persons/km2),Employed (no.),Unemployed (no.),In the Labour force (no.),Total persons aged 15 years and over (no.),Median equivalised total household income (weekly) ($),Land area (ha),Median weekly household rental payment ($),Average family size (no. of persons),Total families (no.),Total dwellings (no.)
0,206041506,15573.0,NaN,10745.0,762.0,11430.0,16028.0,1587.166689,NaN,404.305913,2.600,3876.0,9920.0
1,206041124,7116.0,NaN,4687.0,464.0,5139.0,7416.0,1589.098519,NaN,410.220254,2.600,1146.0,2939.0
2,206041117,15786.0,NaN,10959.0,1395.0,12180.0,17725.0,1537.442265,NaN,379.503859,2.352,2893.0,11453.0
3,206041503,9535.0,NaN,7455.0,642.0,8050.0,11228.0,1408.775034,NaN,357.934956,2.300,2040.0,7717.0
4,206041505,15961.0,NaN,16850.0,1630.0,18329.0,23494.0,1272.073290,NaN,368.057013,2.200,4502.0,13446.0